### ISSUE TITLE
App restarts on bluetooth connection to keyboard

### ISSUE THREAD

**Issue by zeguramente** [gsantner/markor#1005]
#### General information

* **App version:** 2.2.10
* **System:** Android 6

#### Description

Everytime when a bluetooth keyboard has connected or disconnects the app is restarting.
I'm using a Logitech G613 keyboard. I also tried another bluetooth keyboard with the same effect.

**Comment by gsantner** [comment]
Hey,  
Markor doesn't use anything with bluetooth itself. This should be something your Android OS should deal with, sure it's an Markor specific issue? I don't have any bt keyboard, so unless getting helpful logs, or somebody else takes insight you won't get any fix.

**Comment by zeguramente** [comment]
Hey,
I tried several apps. It seems like some apps don't close on bluetooth connection and some do :o

After a digging a bit in the web. I found something on stackoverflow. 
[https://stackoverflow.com/questions/31032042/android-get-restarted-once-it-is-connected-or-disconnected-to-bluetooth-device](url)
 I'm not sure wether this helps.

**Comment by gsantner** [comment]
As far I understand it's to be expected behaviour by Android OS. I want to keep the app adapting accordingly, so not making a change here. Doing what the thread says (ignoring `keyboard` config changes) would mean no adaption of UI to when virtual keyboard pops up, and text is then below the keyboard & invisible.
