### ISSUE TITLE
markdown: Improve bold edit highlighting

### ISSUE THREAD

**Issue by glocalglocal** [gsantner/markor#1021]
Markor 2.3.2 on both my phone (Android 6) and tablet (Android 4). 

In Edit, <asterisk><asterisk>word1<asterisk><asterisk><space>sentence<space><asterisk><asterisk>word2<asterisk><asterisk> is displayed as a single block in bold, including the sentence inbetween that shouldn't be in bold. This happens every time in Edit but never in View.

**Comment by harshad1** [comment]
Could you post an example? A screenshot would be nice too, if possible.

**Comment by glocalglocal** [comment]
![test1](https://user-images.githubusercontent.com/16408198/92598982-20a7b000-f299-11ea-8b4d-07cbd685a1c5.jpg)
![test2](https://user-images.githubusercontent.com/16408198/92598989-243b3700-f299-11ea-9673-4589c2a520db.jpg)

**Comment by harshad1** [comment]
The issue here is that Markor's bold pattern regex doesn't follow all the actual markdown rules. If you are able to come up with a better regex pattern, I can make a PR to update markor.

Current regexp pattern:
`(?<=(\\n|^|\\s))(([*_]){2,3})(?=\\S)(.*?)\\S\\2(?=(\\n|$|\\s))`

[Commonmark spec](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis)

**Comment by harshad1** [comment]
Also, here is a [regexp tester](https://www.freeformatter.com/java-regex-tester.html) I like to use.

**Comment by gsantner** [comment]
Most important: That performance doesn't decrease consideriable. If it's way worst we can live with minor syntax highlighting-only display issues.

**Comment by gsantner** [comment]
There were some recent improvements for this, closing
