### ISSUE TITLE
Partial text from document appended to end on save with 2.3.1+

### ISSUE THREAD

**Issue by ciphersimian** [gsantner/markor#1030]
#### General information

* **App version:** 
v2.3.1+ F-Droid

* **System:** 
Android 8.0.0

#### Description
My usage of Markor is very simplistic.  I only use plain text files with no extension.  Frankly Markor does a lot more than I want it to but I have not yet found a simpler alternative.

I recently started having problems where bits of the ends of my notes would get duplicated at the end on save.  I tracked it down to something introduced between 2.2.10 and 2.3.1 (I went back to 2.2.10 and no longer have the issue).

#### Log

**Comment by gsantner** [comment]
havent reproduced but related

<https://github.com/gsantner/markor/commits/master/app/src/main/java/net/gsantner/markor/activity/DocumentShareIntoFragment.java>

Simplify file opening, overall and from widget, closes #873 (PR #977 by @harshad1)

**Comment by gsantner** [comment]
Hmm I just tried to reproduce the issue but it doesn't happen here. Tried sharing into existing txt file and md file.

Please create a screenrecord and share it here so I can fully see whats going on for you.

If somebody else has the issue please comment here.

**Comment by JonFStr** [comment]
**General Information**
- Android 8.0.0
- Markor build info:
  Package: net.gsantner.markor
  Version: v2.3.2 (116)
  Flavor: Default (release)
  Build date: 2020-07-29T08:02Z
  ISource: F-Droid
  VCS Hash: 73c73f21ffecbdec2d35bae8e0472980572af8e5
- Notebook-folder: external storage (microSD; i.e. /storage/C3E5-161A/Notes)

**Description**
I have the same problem, when I open an already existing file and delete some text out of it, the last characters duplicate so the fiesize doesn't shrink.

**Steps to reproduce**
See video at https://upload.disroot.org/r/aRacNUvx#DJSnMNQcobbW9vt/ik54j3tkbK6xUvuU0xfZn/TAFJg=
Password: `markor`
The file is only available for 30 days, feel free to upload it somewhere permanently or send me a message if you need it at a later point in time

**Possible cause:** The problem is that when overwriting the file with content that is smaller than the previously stored content, the overwrite does not delete the not overwritten content but just keeps it.

At the moment I am on vacation, but when I'm back home I could maybe look into this myself.

**Comment by harshad1** [comment]
@JonFStr I can't reproduce this on my pixel 3.

Perhaps this is an SD card / flush issue? When you are back, could you try to see if this happens when you use the onboard storage?

**Comment by JonFStr** [comment]
You're right, it only appears on the SD card.
I now moved the folder to the internal storage and don't have the problem anymore; thanks for your help!
