### ISSUE TITLE
does not jump to end of markup document

### ISSUE THREAD

**Issue by ruko42** [gsantner/markor#1055]
#### General information

* **App version: v2.3.2 (116)** 
* **System: Android 8.0.0,  Samsung Galaxy A5 (2017) SM-A520F** 

#### Description
Can not jump to the end of a markup document (size is 41 PDF pages, if exported).
Jumps to about 1/3 of text in view mode.
Does NOT jump in edit mode.

**Comment by gsantner** [comment]
Can you please send me the document via [email](https://gsantner.net/)? I cannot reproduce the issue, might be specific to the document and it's assets.

If no response gonna close this in some days.

**Comment by ruko42** [comment]
I sent you a file, where I have had the error. Could you verify the behavior?

**Comment by gsantner** [comment]
Hey sorry for late response, I had lots of personal and day job todo.

![screen-20201203-235937](https://user-images.githubusercontent.com/6735650/101098751-c1b9b480-35c3-11eb-8801-5ef50f2e6b4a.gif)


No I cannot spot any issue on this file. Give it a try with latest Markor update, or next one (>=2.4.1 / 2.5.0)

**Comment by glocalglocal** [comment]
In v2.11.1 I see what I think @ruko42 describes. While viewing markdown files I tap on the `Jump to bottom` button and the display scrolls half-way down the text. I tap again and it scrolls to the top. 

This has been happening every time with different .txt and .md files, ever since I installed Markor years ago, and on different devices running Android v7 and v13.
