### ISSUE TITLE
Complete rework of filesystem fragment

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#115]
#### General information

* **App version:**  v0.2.1

#### Steps to reproduce
Target is to completly rework the filesystem view/fraent. Currently the app uses adapterkit (Gradle: `com.mobsandgeeks:adapter-kit`) to display the filesystem adapter. This should be replaced by some at least maintained library, or self created.

#### Expected result
The target is to remove the dependecy on the said library and to just use normal layout/adapter/recyvlerview combination with sections.

The said library was last updated 4 years ago and we only use a very small part of it, which is not much lines away from doing it without the library.

**Comment by gsantner** [comment]
From #115:

* add a third section (most bottom) to the adapter, hidden files
*  hide this whole new section by default
* show on toolbar toggle (in filesystem fragment menu) active these unsupported things there

**Comment by gsantner** [comment]
<https://github.com/afollestad/sectioned-recyclerview> sounds like the best alternative

**Comment by gsantner** [comment]
Will also fix this.

![image](https://user-images.githubusercontent.com/6735650/34693520-38438d86-f4c4-11e7-9a23-00694e4f65c8.png)

**Comment by Offerel** [comment]
Unfortunately I can't help with the development due to a lack of know-how. Nevertheless, this is one of the most important new features for me. It would be useful for me to display non-markdown files like *.pdf in the file list (open them with a separate app) and hide subfolders. 

Can you possibly give us an approximate idea of when we can expect a first test release?

**Comment by gsantner** [comment]
Complete rework wille be part of the 1.7.4  release and will be featured in the 1.8 blog post.
