### ISSUE TITLE
Support the new storage APIs including scoped storage, SAF etc

### ISSUE THREAD

**Issue by maggu2810** [gsantner/markor#1172]
This is a feature request to add support the native file manager / android storage API  additional to use your own file browsing. 

Why?
Hm, this request is added because of a personal interest. :wink: 
I moved my shared files to a private server that can be accessed by smb.
After that I would like a simple way to access that files on my android system.
There is: https://github.com/google/samba-documents-provider
Google itself does not continue that project but there is an APK on F-Droid: https://f-droid.org/en/packages/com.google.android.sambadocumentsprovider/
After configure a samba share, this share will be shown in the android file browser and can be accessed by apps using it.

It would be great if this could be added to Markor so we could edit files on samba shares transparently without needing to copy it to the phone, edit it and copy it back.

**Comment by gsantner** [comment]
Primary focus is offline file editing, I wont add any sync provider library. If you add one everybody comes with their favourite thing of the day and suddenly you have a bloated app with hundreds of libs.

**Comment by maggu2810** [comment]
I get your point, but perhaps you miss understood mine.
AFAIK you do not need to add any provider to your app, you just need to support the native file manager.
Install the sync provider and you get smb supoort on androids native filemanager and e.g. tested with collabra you can use smb located documents transparently without modification. Only requirement is to support the native file manager.

**Comment by gsantner** [comment]
Well, it requires rewrite of EVERYTHING, so dont expect it soon - unless some contributor comes up and is willing to take some weeks.

 Also, its massive slow (SAF) compared to native file access.

**Comment by theScrabi** [comment]
Hi, I am one of the developers of the ownCloud android application.

Android is going to switch off accassing the shared storage using java I/O. This leaves apps to only use. SAF for accessing shared storrage.

Additionally some storage apps like ours, and propably also NextCloud will provide the files only through SAF in the future.

If you could please consider giving SAF implementation a higher priority. It would be great if we could use this app on future android versions and have better abilities to sync notes :)

**Comment by aubreyz** [comment]
> Android is going to switch off accassing the shared storage using java I/O. This leaves apps to only use. SAF for accessing shared storrage.

I think this is part of the problem. Google made storage access a moving target and then set bizarre criteria for apps being allowed onto the appstore at all. Several great apps (such as simpletask) pulled the plug totally on app development (and then later withdrew from the playstore completely) because of this game and because they tried to play it.

**Comment by beroal** [comment]
> Google made storage access a moving target

I would like to insert my 5 cents on Storage Access Framework (SAF). I agree that Android is a moving target, and this makes it a PITA for users and programmers. While SAF is seen as a yet another annoying change by Google, it's useful for security. Probably, because it's not Google's idea, but Google's implementation of an old idea called _powerbox_. With powerbox, an application only has access to files that a user wants to edit with this application. Without, the application has access to the entire Shared Android storage.

Google also uses SAF for virtual file systems, although Linux FUSE does this too. This is another reason people like SAF. It's what the original poster talks about.

I would like SAF support in Markor for security and to access files in the Termux internal storage. The only text editor that supports SAF and I'm aware of is closed-source QuickEdit. Is there any way to donate to Markor?

> Also, its massive slow (SAF) compared to native `File` access.

Is this an issue for text files? How large can they be?

**Comment by gsantner** [comment]
Markor now targets Android SDK33, uses AndroidX and works way better with other apps now & reading/writing back files.

Closing
