### ISSUE TITLE
Feature request: hide file extension in list

### ISSUE THREAD

**Issue by poisonborz** [gsantner/markor#1199]
As a wild guess a lot of users use just a single file format. For them, displaying the file extension is redundant. It would be great to have an option to hide the file extension, as it would provide a cleaner list.

**Comment by gsantner** [comment]
If theres one thing on Windows thats probably "turn on file extensions", because you may click something very bad.

And no, Markors file manager shows all files, and you can open not-supported files in external app. So it makes totally sense to show the extension.

For example, I also have pdf's and jpg's in the same folders.
