### ISSUE TITLE
Please add more syntax to preview 

### ISSUE THREAD

**Issue by shockergit** [gsantner/markor#1225]
Please add this syntax to preview
==Love==
^^Love^^

**Comment by harshad1** [comment]
These aren't standard markdown, are they?

**Comment by gsantner** [comment]
I haven't seen it like that in any spec, or in use at least. And [CommonMark](https://spec.commonmark.org/0.29/) doesn't mention it.

Use 

```
## heading

...or

heading
=========
```

**Comment by shockergit** [comment]
No its not a syntax for heading. And its not standard syntax but it works in ghost writer, markdown monster and iawriter i found it from markdown monsters sample tutorial file.
==ggg== for highlighting
^^ghhh^^ for i dont know what you call that but it moves the text upwards like ⁸⁸⁰⁸

**Comment by gsantner** [comment]
You can check our Markdown parser, Flexmark if it supports that. <https://github.com/vsch/flexmark-java/wiki>.

Otherwise, CommonMark doesn't have it in it's specification at last, and if the parser not supports it - won't happen for Markor.

**Comment by gsantner** [comment]
You can check our Markdown parser, Flexmark if it supports that. <https://github.com/vsch/flexmark-java/wiki>.

Otherwise, [CommonMark](https://spec.commonmark.org/0.29/) doesn't have it in it's specification at last, and if the parser not supports it - won't happen for Markor.

However I suggest you to use something that is common supported and not something special syntax a application decided to create. You can find a syntax that should work in EVERY markdown application here - https://raw.githubusercontent.com/gsantner/markor/master/samples/markor-markdown-reference.md .
