### ISSUE TITLE
Files not editable with markor(e.g. images) should be displayed below other files and grayed out in the file list.

### ISSUE THREAD

**Issue by Asmageddon** [gsantner/markor#1267]
They are not what you are using the app for, and when you import images, the file list gets quite trashed.

**Comment by gsantner** [comment]
> should

Personal opinion

> Files not editable

You can try to open anything with Markor, you get the question if you want to, when you click a file. Does not mean it will work, but at least you can try. By your suggestion a .sql file would be sorted differently than a .txt just because one is known and the other not.

I don't want to make non-obvious required changes here. Sort by applies to everything and shouldnt produce a third or fourth group.

**Comment by Asmageddon** [comment]
It really gets difficult to navigate the file list when 3/4 of it is images and they're only minimally visually distinct from markdown files.
