### ISSUE TITLE
Centralized data storage please

### ISSUE THREAD

**Issue by Martin-Maat** [gsantner/markor#1330]
I like what I've seen so far, well done. There is one major shortcoming though: notes can only be stored locally, on the device used for editing. This makes it useless for my purpose.

When I am in bed before I go to sleep I am holding my tablet. During the day when I am out I have my phone with me. I want to have my notes accessible at all times, wherever I am, whatever device I happen to be holding. Whatever I started on one device I want to be able to continue on another.

I am asking for support to store the data on a server. WebDAV would be great for me, other means could make other people happy. It would have to be smart, making sure different clients do not overwrite each other's work. Either by locking or by handling conflicts gracefully, offering a merge process if needed.

If you get this right as well you will likely have the notes app of choice.

**Comment by gsantner** [comment]
focus is on working offline and being slim. I don't think off adding sync libraries to the app. Then Markor is no different than any other generic bloat app you can find in stores.

you know what happens when I add webdav? the next one asks for nextcloud. the next one asks for onedrive. the next one asks for gdrive. aaand it's bloat all over place.

**Comment by gsantner** [comment]
focus is on working offline and being slim. I don't think off adding sync libraries to the app. Then Markor is no different than any other generic bloat app you can find in stores.

you know what happens when I add webdav? the next one asks for onedrive. the next one asks for gdrive. the next one asks for nextcloud. aaand it's bloat all over place.

this topic has been brought up many times here on github and in chats, answer is the same.

**Comment by Martin-Maat** [comment]
Too bad, I will continue my search then.

By the way, bloat is stuff you don't need. If these connectors were implemented in separate modules you could offer to delete the ones the user does not use. Mean and lean and above all, useful.

**Comment by Self-Perfection** [comment]
@Martin-Maat syncing inside app is not the only way to get data synced. This can be accomplished by external tools as well. I use Syncthing to get my Zim notes synced across devices including Android device on which I use Markor for viewing/editing.  I daresay this approach has numerous advantages over WebDav access to notes on central storage. For instance notes are kept as local copies so they are available even when internet is not. Maybe you can give this approach a try.

[Syncthing + Markor tutorial](https://gsantner.net/blog/2020/04/04/markor-how-to-use-syncthing-for-sync.html)
