### ISSUE TITLE
Enhancement: Allow image link syntax to include other markdown/text files

### ISSUE THREAD

**Issue by add1989** [gsantner/markor#1404]
Hi,

I use Markor extensively with a lot of Markdown files. I have often wished for a feature that I have now seen working in Obsidian, and I wondered whether it would be considered to be implemented in my favourite mobile text editor - Markor! 😁

Basically, I would like to use the embed image syntax to also include/embed other markdown files.

For example:

```
![My MD File](my-md-file.md)
```

In this example, the contents of that markdown file would also be displayed in the current file when in view mode.

As I mentioned, for reference, there is a working implementation of this in the new Obsidian mobile app.

**Comment by gsantner** [comment]
Your example is more or less a link to a file, which already should open the file when yiu click it.

Embedding documents recursive is not something I want to add.

**Comment by add1989** [comment]
Hi gsantner,

Just to confirm, I wouldn't expect to do this in a nested fashion... only 1 level of inclusion would be needed.

That way, you could do something like create a dashboard note and include 'weather.md' - the contents of which could be the output of a script. Or select a quote of the day etc. Other less gimmicky use cases would be possible too, particularly relating to Zettelkasten - where I have many small notes and would sometimes like to include/embed them into other notes for context.

If it's something you really don't want to do, would you accept a pull request from someone else instead, or not even that?

**Comment by gsantner** [comment]
Markor is not a Markdown parser, so you ask more on the wrong place. Markor uses a Markdown parser but not implements one of it own.

Anyway, our praser does not support it <https://github.com/vsch/flexmark-java/issues/404> and even when, it would be mainly about including html files, not unparsed markdown files. <https://github.com/vsch/flexmark-java/wiki/Extensions#jekyll-tags>

Aside that, it's (including md files directly) not something most Markdown software supports and pretty specific to your other software. I want focus on being more compatible with most software rather than hacking in a solution that just one specific one supports.  
If you are interested in not having some kind of vendor-lockin even though you use markdown..I rather suggest to you to not make use of this feature. Thank me later, when you want to use other tools, converters and stuff, where it wont work either.

Closing as wont fix
