### ISSUE TITLE
Renaming files to change case is not possible

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#1481]
## General information
* App version: 2.8.0 (124)
* Android version: 11
* Device: pocophone x3
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

When I try to rename files but only change the case then I get an error that the file already exists.

example

Aaa.adoc => aaa.adoc

But I can rename files in normal file explorers.

**Comment by gsantner** [comment]
Android normal /storage/emulated/0/ isn't obvious non-case-senstivite, but it is. <https://stackoverflow.com/questions/6502712/isnt-android-file-exists-case-sensitive>.

I have only a file /sdcard/todo.txt and the File::exists(/sdcard/tOdo.txt) check returns true for it.

![grafik](https://user-images.githubusercontent.com/6735650/140398338-e0bce27b-ef5d-4437-b900-c65203927c3f.png)

**Comment by njohnson-oss** [comment]
I think this issue should be reopened.

I independently discovered [this trick](https://github.com/gsantner/markor/issues/2154#issuecomment-1810569867), but non-technical users who don't know about filesystem case sensitivity may resort to more inconvenient or error-prone methods, like deleting and recreating the file.

There is no fundamental barrier preventing renaming to a different case, so shouldn't Markor's file rename dialog abstract away this quirk as well, for user convenience? Why make users do it manually, if it can be automated?

**Additional Information:**

It seems like this issue is handled differently across Android applications.

* [Fossify File Manager](https://github.com/FossifyOrg/File-Manager) handles this correctly, with no warnings, errors, or surprises
* [The default Android file manager](https://source.android.com/docs/core/ota/modular-system/documentsui) handles this incorrectly, appending a " (1)" to the renamed file

**Comment by gsantner** [comment]
> There is no fundamental barrier preventing renaming to a different case

There is. To your filesystem, HeLlO.txt and Hello.txt are treated the same.

**Comment by njohnson-oss** [comment]
> There is. To your filesystem, HeLlO.txt and Hello.txt are treated the same. Case insensitive fileystem.

A case insensitive filesystem is a fundamental barrier to having both of those files in the same directory simultaneously. It is not a fundamental barrier to renaming one to the other.

Instead of putting up a warning, why not just solve the issue for users?

**Comment by gsantner** [comment]
Merge requests are welcome.
