### ISSUE TITLE
[Feature Request] hide menu buttons

### ISSUE THREAD

**Issue by tunbridgep** [gsantner/markor#1486]
I'm using the latest f-droid version (2.8.1) on my Motorola One Vision

I really like this app, but one of the things I don't like is that, if there's a feature I don't use, it takes up space on the screen and it takes up space in my applications drawer.

For example, I don't use the todo.txt support, because I already use caldav to manage my task list (I've been using it for years, but might switch to todo.txt eventually).

While it's far from a deal breaker for me, it's annoying having the button in the menu bar at the bottom, and it's annoying having the "To Do" app in my app drawer. I know I can turn off the Todo app in my app drawer but it also gets rid of quick note, which I do use.

I'd like to request a feature to possibly improve screen real estate and make an easier use case for anyone who doesn't use all the features of the app, in a way that hopefully doesn't require much effort to implement.

So I propose the following changes:

- Remove the "Launchers" checkbox from the settings menu
- Add a new menu to the settings screen, titled "Show/Hide menu items"
- upon opening it, it has 4 selections: Files, ToDo, QuickNote and More
- Each of these has 3 settings available
  - "Show on menu" this shows the button for that feature on the menu
  - "Open by default" this will open that page by default when starting the app. This setting can only be set for one item and overrides the previous
  - "Show in App Drawer" this will make this item appear as an application similar to how it does now.
- if only one item (or none) are set to "show in menu", the menu at the bottom of the screen won't appear, giving us more space to work with.
- If the "More" button is hidden from the menu, it should display in the Hamburger menu instead so we can still see things like version information.

My ideal use case would look like this:
Upon running the application, I want just a markdown editor, nothing else, to edit my notebook. I also want an application shortcut in my app drawer for quickly adding notes, but don't want it in the menu when I'm editing my normal markdown documents. Others will likely have other use cases, and hopefully this feature request caters to others who want to adapt their workflows in various ways too.

This allows people to use this program as exclusively a markdown editor if they want to. Or exclusively a todo.txt manager. Etc.

**Comment by gsantner** [comment]
> one of the things I don't like is that, if there's a feature I don't use, it takes up space on the screen and it takes up space in my applications drawer.

I understand that point, for that reason you can disable the additional launchers as you noticed.

> While it's far from a deal breaker for me, it's annoying having the button in the menu bar at the bottom, and it's annoying having the "To Do" app in my app drawer. 

Markdown, todo.txt (QuickNote, ToDo) ARE one of the core features of the app, and I don't want them to be dismissible by a myriad of settings.

> I know I can turn off the Todo app in my app drawer but it also gets rid of quick note, which I do use.

You can create a pin/launcher shortcut to any textfile. Be it the special QuickNote file, or any other textfile. Not bound to the legacy launchers.

![grafik](https://user-images.githubusercontent.com/6735650/140444144-c6a57b1f-3735-43b2-a7b5-fc6749d356c4.png)

Sorry to disagree, it's quite specific to your personal wanted ussage. I'm more about to slim menus and settings options, instead of introducing a blast of new ones. I won't add 3x4=12 new settings options, with resulting complex logic - just to ged rid of project core features.

Note that you can also change the quicknote & todo file to any of the current formats (plaintext, markdown, todo.txt, zim).   You are not bound to use/have todo.txt on the app main screen, you can also have markdown everywhere (I know this actually is something what users use currently).

**Comment by gsantner** [comment]
> one of the things I don't like is that, if there's a feature I don't use, it takes up space on the screen and it takes up space in my applications drawer.

I understand that point, for that reason you can disable the additional launchers as you noticed.

> While it's far from a deal breaker for me, it's annoying having the button in the menu bar at the bottom, and it's annoying having the "To Do" app in my app drawer. 

Markdown, todo.txt (QuickNote, ToDo) ARE one of the core features of the app, and I don't want them to be dismissible by a myriad of settings.

> I know I can turn off the Todo app in my app drawer but it also gets rid of quick note, which I do use.

You can create a pin/launcher shortcut to any textfile. Be it the special QuickNote file, or any other textfile. Not bound to the legacy launchers.

![grafik](https://user-images.githubusercontent.com/6735650/140444144-c6a57b1f-3735-43b2-a7b5-fc6749d356c4.png)

Sorry to disagree, it's quite specific to your personal wanted usage. I'm more about to slim menus and settings options, instead of introducing a blast of new ones. I won't add 3x4=12 new settings options, with resulting complex logic - just to get rid of project core features.

> This allows people to use this program as exclusively a markdown editor if they want to. Or exclusively a todo.txt manager. Etc.
> Upon running the application, I want just a markdown editor, nothing else, to edit my notebook. 

Note that you can also change the quicknote & todo file to any of the current formats (plaintext, markdown, todo.txt, zim).   You are not bound to use/have todo.txt on the app main screen, you can also have markdown everywhere (I know this actually is something what users use currently). In the same way, you can also exclusively only use todo.txt only, if you want to.   
Really - the only two special files are these two, and users can freely configure the format for both.
