### ISSUE TITLE
File List Intermittently Disappear or is Slow in Samsung Galaxy Fold 3

### ISSUE THREAD

**Issue by JCalinawan** [gsantner/markor#1513]
## General information
* App version: v2.8.0
* Android version: 11
* Device: Samsung Galaxy Fold 3
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

I've been using Markor on Android 10 with a Microsoft Surface duo with no problems, and today I upgraded to a Samsung Galaxy fold 3 running Android 11. When I launch Markor, the file list takes a long time to come up (approx 1 minute), and when it does, and I randomly open files and close them, the file list (that lists all the filenames) will disappear for approx 1 minute before I can open files again. And then, the file list will disappear, repeating the cycle. Does the app work with Android 11? Is there a setting that I need to toggle on/off? Thank you so much for your help.

Regards,
Jonah

**Comment by gsantner** [comment]
> Does the app work with Android 11?

My daily device is Android 11 since about a year. So yes I guess.
I don't have neither mentioned device though, and I don't know anybody who has one of these either.

This is not normal, file manager loads instantly here. And no, there is no special thing to configure, it should work out of the box.

> App version: v2.8.0

Update to the latest version, [v2.8.3](https://f-droid.org/en/packages/net.gsantner.markor/#Packages), it may help.

**Comment by JCalinawan** [comment]
Ahh, thank you so much. The Google play version had 2.8.0, so I thought I had the most recent version. I upgraded to the newest version from your provided link and now it works! Thank you!

**Comment by gsantner** [comment]
OK! You can close this then 😄
