### ISSUE TITLE
Slow File List display

### ISSUE THREAD

**Issue by pudah** [gsantner/markor#1656]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

I am seeing odd behavior with version 2.8.6 that I did not see in version 2.8.4.

When I close a file and return to the file list, it takes a long time for the list to display. I usually get a blank list and a shruggie ¯\_(ツ)_/¯ appears for 5-6 seconds, then the list of files finally shows. 

Sometimes the list shows for a second or two before the blank list with shruggie.

### Steps to reproduce

1. View a file
2. Leave the file
3. Wait for the file list to display

### Information

Android version: 11
Device: Samsung Tab S6 Lite
App Version: 2.8.6(130)

### Source

F-Droid

### Format / File type

No

### Additional info / Log

```shell
It seems to be related to the number of files in the folder.

When I view files in small folders with not very many files, leaving the file and returning to the file list, it displays almost immediately.

But my main Notebook folder contains about 275 files. Viewing a file in this folder, then closing the file to return to the file list exhibits the display issue.

There are no problems with the file list display for this same large folder in version 2.8.4
```

**Comment by harshad1** [comment]
I believe android 11 slowed down file access considerably. Is it possible that you were on an older version of android when you didn't have these issues?

**Comment by pudah** [comment]
No, that isn't possible. I've been on Android 11 for months now and have gone through least version 2.8.3 and 2.8.4 while on Android 11.

I even uninstalled 2.8.6 and reinstalled 2.8.4 to make sure that I wasn't imagining what I was seeing, before opening an issue.

I had missed updating to version 2.8.5 when it came out. If I get time later today, I'll try that version and see if it exhibits the same behavior as 2.8.6.

**Comment by gsantner** [comment]
try a apk from recent builds (GitHub Actions tab), if it's better there. I recently did some I/O improvements by caching the fs states. The majority of time that slows things down **is** filesystem calls - which is things like modification date, creation date, filesize, list folder, ... and that scales linear by the number of files in a displayed folder.

> Sometimes the list shows for a second or two before the blank list with shruggie.

I assume you already have a build that includes this caching, which probably happens here (cache value displayed, new data starts to load).  

Though overall still hard for me to diagnose why specifically on some devices/versions it is **soooo** slow. I have a blog post folder containing 300 files and it loads instantly.

**Comment by gsantner** [comment]
try a apk from recent builds (GitHub Actions tab), if it's better there. I recently did some I/O improvements by caching the fs states. The majority of time that slows things down **is filesystem calls** - which is things like modification date, creation date, filesize, list folder, ... and that scales linear by the number of files in a displayed folder.

> Sometimes the list shows for a second or two before the blank list with shruggie.

I assume you already have a build that includes this caching, which probably results into your secondary description (--> cache values displayed, new data starts to load).  

Though overall still hard to diagnose why specifically on some devices/versions it is **soooo** slow. I have a blog post folder containing 300 files and it loads instantly.

----

![image](https://user-images.githubusercontent.com/6735650/163232095-ccfa36a0-4835-4511-9180-e6436cc89c59.png)

please also use search, you explicitly confirmed you did. slow loading folder list is being reported recurringly ... many times. Which means useless double discussion, and wasting time for maintainence instead of developing. More noise = less fixes, less features.

**Comment by pudah** [comment]
My apologies. I really did search. But I must not have done a very good job as I didn't find anything that looked like the same issue.

I will try recent apk per your suggestion and report findings.

**Comment by pudah** [comment]
I tried one of the recent Actions apks (one dated Apr 18).

It seems to almost completely eliminate the delayed file list display.

But I think it created a delay in displaying larger files.

**Comment by gsantner** [comment]
like in - loading at editor?

**Comment by pudah** [comment]
With the Actions apk, the file display issue occurs if I open a larger file. I tap on a file in the file list and I get a blank screen - nothing but the status bar and navigation bar - for 5 or 6 seconds. Then the file contents and the rest of the user interface displays.

It seems to happen with smaller files also, but it takes less time - maybe only a second - for the display to show so it is not as noticeable.
