### ISSUE TITLE
Zim: First sentences consisting of one word treated as list index

### ISSUE THREAD

**Issue by Self-Perfection** [gsantner/markor#1729]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

First sentences consisting of one word seem to be considered a list indexes in zim notes.

### Steps to reproduce

1. Create zim file with following content
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2022-05-27T10:42:29+04:00

====== Markor test ======

Wikipedia. Test.
``` 
2. Observe that Markor shows "1" instead of "Wikipedia". Thats not what I would expect! 
![image](https://user-images.githubusercontent.com/3757038/170837896-f8e36e1f-0a16-41cd-b702-fc204cde7c97.png)

### Information

Android version: 9
Device: Xiaomi Mi A1
App Version:  2.9.0

### Source

F-Droid

### Format / File type

Zim

### Additional info / Log

According to zim sources it considers only single character as an numbered list index: https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/4d38bb8f5f693e50a4a5f83e4c95eb049f6e9786/zim/formats/wiki.py#L51-L61

**Comment by gsantner** [comment]
Probably some `wordcharacter+` regex match converting it

**Comment by fredericjacob** [comment]
Numbered list items in zim can contain either numbers or letters (either a./b./c./... or 1./2./3./...). There's a pre-conversion step from zim to markdown so that the markdown html converter (for view mode) can be used for zim as well. But the used regex expression for matching list items is obviously too greedy and can match complete words: https://github.com/gsantner/markor/blob/d2996a86b249321536ff6af99562c1355670457b/app/src/main/java/net/gsantner/markor/format/zimwiki/ZimWikiTextConverter.java#L75

Edit mode regexes for numbered lists work fine, so this should probably be changed to something like this regex here: https://github.com/gsantner/markor/blob/d2996a86b249321536ff6af99562c1355670457b/app/src/main/java/net/gsantner/markor/format/zimwiki/ZimWikiHighlighter.java#L37
I can fix and test this when I find some time. But whoever wants to dive into it right now - feel free to work on this and create a PR!

**Comment by gsantner** [comment]
Preferably keeping it for you when you want to. I don't use Zim on at all, a Zim user knows the everyday needs and possible issues better.
