### ISSUE TITLE
Superfluous warning

### ISSUE THREAD

**Issue by citizen1277** [gsantner/markor#1732]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

When saving files to or opening files from the SD card, the following  warning appears and persists indefinitely at the bottom of the edit screen:
"Warning! The app doesn't have permission to save this file, all changes will be lost.  There is no possibility to resolve the problem or to confirm something, Android denies any access here."
All files do, in fact, save normally.  It persist no matter how  many times I grant and revoke permissions and restart the app.

### Steps to reproduce

The warning appears and persists indefinitely when saving files to and opening files from SD card.

### Information

Android version: 8.0.0
Device: SM-G930V
App Version: 2.9.0 (132)

### Source

F-Droid

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment]
there are multiple discussions on either issues/discussiona already.

**Comment by citizen1277** [comment]
Where?

**Comment by gsantner** [comment]
just searching "warning" shows it. please search before creating new issues/discussion. 

thanks.

**Comment by citizen1277** [comment]
There is only one that is similar, from April 2020, but the app verson is different and they were running a rooted version of Cyanogenmod 12, not standard Android  8.0.0.  Also, the suggested solution on that thread does not work in my case, as I've already stated in the original post.  Attention to detail is one of the keys to good programming.  I think you should work on that.

**Comment by gsantner** [comment]
**It is still the same issue and nobody worked on that.**

 Also don't try to teach me better, I'm here to make a good piece of software and take my personal time to answer yours (& others) issues and questions. There is a reason WHY I ask people to search for duplicate & already open things. Less time on answering things, is more time for development. More duplicate stuff, like yours, means less time I have for development.

So - answering this I could have already fixed something else. If you want, have the time, and the skills please work on the issue, work on the code - instead of pointing at somebody wasting his **free & leisure time** with reading your stuff. Thanks.

**Comment by citizen1277** [comment]
Being hostile and dismissive towards people who are reporting bugs wastes everyone's time.  Marking issues as closed when nothing has been done to solve the issue wastes everyone's time.

**Comment by gsantner** [comment]
Good to hear you agree on that. So next time, please use search and write there instead of repeating.  
That's it.

**Comment by gsantner** [comment]
By the issue template, I specifically ask you to do this duplicate search, and you confirm by clicking the checkbox you do it. Asking "where?" tells me you did not and ignored this.
I'm really happy to help, but not when people ignore things and start being aggressive towards me personally when pointing out to follow the rules. When maintainers tell you, this is duplicate, please write at the other place.  
Next time, please use search and write there instead of repeating on a fresh new place - when maintainers specifically ask you for it. In any project.  
That's it. Whoever is the maintainer of the next project you comment on - will thank you.
