### ISSUE TITLE
Format/File type detection when opening preview

### ISSUE THREAD

**Issue by doronbehar** [gsantner/markor#174]
Well first of all, this is a wonderful app.

I usually use it for editing plain text files and I noticed that it gives me a preview of text files as if they were markdown. Text files previews should be opened for `.txt` files by default. A user shouldn't need to press the menu button and choose a format every time he opens the file.

I hope I was understood, thank you for your time.

**Comment by gsantner** [comment]
Currently everything is marked as Markdown, unless todo is in front or end. This is by intention so, because Markors main focus is on Markdown. Markdown is not specific to a file ending, it is a format for plaintext files. And txt is a plain text file.

Heres a article from the markdown mailing list:

```
Markdown isn't meant to take over the format of a file, it's a way to subtly add information to the plaintext. Really, the presence of Markdown is metadata, not a file format.
...
No one opening a text file will be confused if they find Markdown syntax, it's pure bonus.

In this sense, it makes sense to use ".text", ".txt", or whatever other plaintext extension is relevant.
...
An editor which knows nothing about Markdown won't care about the metadata and won't be confused by the variety of "non-standard" extensions, but will display and edit the plaintext just fine.
```
<http://blog.gmane.org/gmane.text.markdown.general>


Nevertheless I am not sure if I will keep markdowm format for .txt extension.

**Comment by doronbehar** [comment]
I understand your philosophy. It's just that I use markor for editing poetry, and I have to switch to plain text format in order to view the line breaks between all the lines of the files I create. That's why it is pretty annoying for me..

**Comment by gsantner** [comment]
poetry as in poems or is that some format too?

**Comment by doronbehar** [comment]
As in poems.

**Comment by doronbehar** [comment]
Thanks!
