### ISSUE TITLE
Add more Files view appearance options

### ISSUE THREAD

**Issue by Asmageddon** [gsantner/markor#1854]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] Is the wanted feature/enhancement present in the latest code version (git master)? Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. No worries Markor and Mordor appear as completely separate applications, you can install both side-by-side and Markor settings are not touched. If so, the change will be part of the next Markor update.

### Description

Right now, navigating multiple folders deep hierarchies of notes, interspersed with image files, is a very janky experience. The list is very monochrome and indistinct. 

The set of features that I'd like isn't large, and entails:
 - Ability to set multiple different colors for files, in place of favoring them to highlight them gold only.
 - Ability to set custom icons(possibly emoji?) for files/folders
 - Option for non-Markor-native files(images, dotfiles, etc) to be displayed below other files, grayed out.
 - Possibly also folder icons being darker, to make it visually distinct where folders end and files begin

### Information

Using crDroid 7.9 on Xiaomi Redmi Note 9 Pro (miatoll)

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment]
> The set of features that I'd like isn't large, and entails:

Keep in mind - Markor is also said to be lightweight. It also has much features. Though much features not means that you need to be able to customize everything to the tiniest bit. Thats also most users dont need, so option bloat & creep.

> Ability to set multiple different colors for files,
> Ability to set multiple different colors for files,

No. This has been asked before, still no wont add.


> Option for non-Markor-native files(images, dotfiles, etc) to be displayed below other files, grayed out.

First you need to define whats a Markor file is, or not. There is also usuallly a popup to let users choose to open in Markor or other file.  
I don't feel like adding another level of complexity to file browsing easier for anybody. Suddenly whatever starts with a is grouped into 3 different pages. Not makes sense, just confuses users. 
 Really, move the files off somewhere else if they are disturbing you. File management is your own decision. --> **No**

> Possibly also folder icons being darker, to make it visually distinct where folders end and files begin

For some people it's too bright ""blinding flash"", for some it could not be dark enough. Hard to find something that everyone likes. At Markor I setted up something that works fine for most users and that in both light and dark mode. If you want to tweak the colors slightly, please experiment with it and make a pull request if you are sure it overall makes it better for both sides.

Closing.

**Comment by Asmageddon** [comment]
@gsantner Respectfully, as great as Markor is at markdown notes, its file organization is sorely lacking. 

It's not meant to be a general purpose file browser, and if I have 20 images in a folder with 4 note files, I don't need or want to see them listed together. It just makes it a nightmare to spot which file is actually my notes, because they all look the same.

Likewise, the favorites are a purely visual feature right now. The change from only having one color to a choice of several is functionally minor, but significantly enhances visual clarity.

**Comment by gsantner** [comment]
> Respectfully

If you want to be respectful, respect the projects goals like lightweightness and KISS principle. And just because you like something doesn't mean everyone like it this way.

> It's not meant to be a general purpose file browser

Why not? It can and is used this way - I don't use any other file managers/browsers actively.

>  and if I have 20 images in a folder with 4 note files,

Thats your decision to put 4 notes and 20 images together. You can also put 20 images in a subfolder "assets". Your decision. And whatever file manager you will use, it will show 24 files as it is, by whatever sort criterium.

> I don't need or want to see them listed together

Your personal preference. Just like mine is to see all files at same time - like in any other filemanger. I visit a folder, I have a sort ctrieria ("by name") and if I have whatever file starting with a is ahead of the file starting with b.

> It just makes it a nightmare to spot which file is actually my notes, because they all look the same.

Again the suggestion, you can layout the file hierachy to your likeness. Your decision.

Now, tell me which file manager does actually do what you want? Making 2 groups (folders, files)  ("folders first") is quite common. But I've yet not used any file browser that makes more special groups (folder, "might be good files", "might be bad files"). 

> Likewise, the favorites are a purely visual feature right now.

Why? You can mark a file as favorite. It is visualized as favorite. And you have a shortcut to view ALL your favorites.

> The change from only having one color to a choice of several is functionally minor, but significantly enhances visual clarity.

More colors might be something you want. What it is also: bloat. 

The only thing I can think about that I have seen in file managers is this: Sorting by MIME-Type.

**Comment by gsantner** [comment]
> Respectfully

If you want to be respectful, respect the projects goals like lightweightness and KISS principle. And just because you like something doesn't mean everyone like it this way.

> It's not meant to be a general purpose file browser

Why not? It can and is used this way - I don't use any other file managers/browsers actively.

>  and if I have 20 images in a folder with 4 note files,

Thats your decision to put 4 notes and 20 images together. You can also put 20 images in a subfolder "assets". Your decision. And whatever file manager you will use, it will show 24 files as it is, by whatever sort criterium.

> I don't need or want to see them listed together

Your personal preference. Just like mine is to see all files at same time - like in any other filemanger. I visit a folder, I have a sort ctrieria ("by name") and if I have whatever file starting with a is ahead of the file starting with b.

> It just makes it a nightmare to spot which file is actually my notes, because they all look the same.

Again the suggestion, you can layout the file hierachy to your likeness. Your decision.

Now, tell me which file manager does actually do what you want? Making 2 groups (folders, files)  ("folders first") is quite common. But I've yet not used any file browser that makes more special groups (folder, "might be good files", "might be bad files"). 

> Likewise, the favorites are a purely visual feature right now.

Why? You can mark a file as favorite. It is visualized as favorite. And you have a shortcut to view ALL your favorites.

> The change from only having one color to a choice of several is functionally minor, but significantly enhances visual clarity.

More colors might be something you want. What it is also: bloat. This is not "the MacOS desktop Finder file manager with 20 color tags".

The only thing I can think about that I have seen in file managers is this: Sorting by MIME-Type. 

Remember: I'm not here to make you happy, you are not my customer and not my boss. If you want something, you need to develop it on your own and make a pull request, or convince me it's for the good. I don't see something in this discussion yet that makes me wanna do anything what you personally would like - it's my time and I do with it what I think makes sense and is good. And if Markor doesn't do what you want and not to your preference, nobody forces you to use it.  
Thanks for understanding.
