### ISSUE TITLE
Suggestion: "two spaces" on the toolbar

### ISSUE THREAD

**Issue by jerry1970** [gsantner/markor#189]
#### General information
* **App version:** 0.3.1

#### Description
I regularly type in lyrics. To prevent the whole verse reading as a single paragraph, I have to type in two spaces at the end of each sentence.

But my keyboard app (SwiftKey) turns this into a period and a space unless I keep some time between typing the two spaces.

Might it be useful also for other people to have a button on the toolbar to add two spaces at the end of the current line? Maybe the cursor doesn't have to be at the end of the line. And maybe the app can check whether there are already two spaces to prevent extra spaces being added.

**Comment by gsantner** [comment]
The app won't restrict to use more than two spaces, and won't restrict where to place them (even if some special button is used).

Other than that, it may be possible but, I'm yet unsure about it, because the toolbar has already quite much items and we cannot just put everything in, it that one can think of.
