### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#192]
It'd be nice if Markor auto-generated a ToC in the beginning of documents, both in preview and in export. Maybe only for files above a certain size/length.

**Comment by gsantner** [comment]
Everybody can do this with the new Javascipt /CSS inject feature. I don't want to bloat Markor with lots of stuff. One can use whats in preference - an option is <http://projects.jga.me/toc/>.

**Comment by Conceptron** [comment]
So, I was able to insert a TOC at the beginning of the preview by inserting the below javascript in the `Preview->Inject` settings option.
```html
<script src="http://projects.jga.me/toc/dist/common.js"></script>
<script>
    $(document).ready(function() {
        $("#toc").toc({
            'selectors': 'h1,h2,h3,h4'
        });
    });
</script>
```
and adding a `<div id="toc"></div>` at the beginning of the markdown file. To avoid editing the markdown file, an **Inject to body** setting could be added in which the `div` could be added.

Also, it would be nice if there was either an **`up` button** in the preview to scroll to the top of the document as clicking a link in the `TOC` scrolls to one heading and to navigate to a different heading I have to scroll all the way up again. Instead of the `up` button there could be **`back` and `forward`** button like in a browser too.

This only allows navigation in the preview though, It would be nice if there was a **navigate using toc** feature in the editor too.

**Comment by gsantner** [comment]
Thanks for taking a look!

* Inject to body: Good idea! PR welcome, 90% same like `inject to head` in implementation.
* TOC javascript: I want all defaults (even uncommented includes) to work always and offline. Please don't include the above for now (also don't want to push javascript files to bundled assets, want it to be compatible on desktop too).
* Navigate to top - available from `Special keys` Text-Module. Thought this is maybe something often used, I'm unsure about if and where we would place it seperatly. We already have thaaaaat amount of toggles and actions. Currently more in the process of combining things. Ideas?

**Comment by 809825706** [comment]
is the function Navigate to top available？
