### ISSUE TITLE
Issue in dealing with Obsidian absolute links

### ISSUE THREAD

**Issue by Klemet** [gsantner/markor#2020]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

In Obsidian, one can use "Absolute" markdown link that are relative to the root of the folder containing your notes.

For example, all of the links to the note **Note1.md** that is in **Folder1** and **Subfolder1** will be like:

```markdown
[Link to Note1](Folder1/Subfolder1/Note1.md)
```

...no matter the note that the link is in.

However, when this link is clicked in Markor, it will be made relative to the note the link is in, leading to a the wrong path.

For example, if **Note2.md** is into **Folder2** and **Subfolder2** and it contains an absolute link to Note1, then clicking on the link in Markor will lead to `Folder2/Subfolder2/Folder1/Subfolder1/Note1.md`, which doesn't exists.

To correct this behaviour, I imagine there would need to be a kind of "absolute path" setting which would ignore the folder of the current note. I couldn't find such a setting in the current versions of Markor.

I thought that this problem had been addressed in #1223; but this doesn't seem to be the case.

### Steps to reproduce

1. Create absolute links to different markdown notes (e.g. via Obsidian)
2. Open one of the note in Markor and click on the absolute the link
3. The link will bring to an empty note with the path being `folder of note with the link/absolute link to the note to be reached by the link`.

### Information

Android version: 11
Device: Samsung galaxy S5
App Version: 2.1.8 (145)

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment]
Essentially, you want absolute links (with no leading slash) treated as relative to the notebook directory?

**Comment by Klemet** [comment]
Yes, I think that this would be it ! I was unsure as if it was a bug or a feature request, though; if it was something that was supposed to be handled by Markor already or not.

**Comment by gsantner** [comment]
Hello, is there any other software which supports this? Usually referencing one document to another is always relative to the current file, be it in Markdown or at the web (file /folder/a.html referencing hello/world.html would be at /folder/hello/world.html).

I just don't feel it's a good idea to make changes just so it works with only <software x> or so <software y> can do whatever want not contained in any specs and suddenly everybody expects it to work everywhere like this.

**Comment by gsantner** [comment]
Hello, is there any other software which supports this? Usually referencing one document to another is always relative to the current file, be it in Markdown or at the web (file /folder/a.html referencing hello/world.html would be at /folder/hello/world.html).

I just don't feel it's a good idea to make changes just so it works with only _software x_ or so _software y_ can do whatever want not contained in any specs and suddenly everybody expects it to work everywhere like this. In the meaning of vendor lock-in.

**Comment by Klemet** [comment]
Thank you for your answer, @gsantner ! And thank you for Markor, it's awesome 😄 !

I haven't found any other app that can deal with that yet, apart from Obsidian's own android app. But it's really slow on older devices like mine, while Markor is lightning fast. But I could search further !

I think I understand your point of view. From my part, I enjoy the possibility of customization that markdown offers, which can adapt to different user priorities. For example, some use wiki links because they're faster to type; some might prefer normal markdown links that contain more context, and so on. On my part, I prefer absolute links because they offer the most context as to were a note is located, and they will only change if the name of the note changes.

On that end, I really enjoy that Obsidian allows the user to choose between these types of links rather than forcing a particular type. There are some many markdown apps and software now that I like the idea of compatibility between them if needed, which requires this kind of tweaks.

I understand that this might sound like entitlement, though; I just wasn't sure if adapting to this type of user preferences was a priority of Markor or not. If it's not, I think the issue can be closed !

**Comment by gsantner** [comment]
> I haven't found any other app that can deal with that yet, apart from Obsidian's own android app.

Sorry to cut but I'm opposed to Obsidian constantly brewing their own stuff instead of going for rather common Markdown syntax that works everywhere. While I try to make Markor open to everybody and all open formats I don't want to support (creating) vendor lock-ins. Otherwise I wouldn't be developing Markor after all and use an existing solution, that does make such  custom stuff that only works _in this program_.

**Comment by brydon349** [comment]
I was interested in this as well. It sounds like this will NOT be supported?

In my case, I feel this simplifies the burden of me always having to be 'folder aware'.

An example. I keep a running list of monthly note files. I use this as my QuickNote file and I store them all in the folder monthly. Currently that means the file /monthly/2024-09.md is my QuickNote file.

Everytime I want to reference another note(file), I need to consider which folder I'm in and, in this case, reference a note in the root with [../main] rather than simply [main]

That's not a massive issue, that's how navigating files/folders works in general. The trailing issue here is in moving files around between folders.

Unless I'm missing something, if I move a file into a sub folder, I have to rewrite all the note references both in that file, and any references to it, to keep them working. If I rename a folder, same.

If this will never be supported, that's fine. In my case, I will work to write a set of scripts to attempt to handle file moving. I don't want to get to a point where I'm hesitating to reorganize my notes simply because there are too many backlinks and links.

For me, this isn't about chasing Obsidian. I would suggest this is how most web servers function. I would prefer to have the same options here, where I can choose to have a root folder (~/notes in my case) and I can reference files relatively ( [[../main]] or reference from root and know that it should work provided that file isn't moved [[/folder/main] which would render to ~/notes/folder/main

**Comment by ruedigerblock** [comment]
Obsidian is just one example that uses a project root for referencing files absolut from the project root folder. 
As a matter of fact every IDE either supports or enforces this behaviour.
I use `vim` with the airblade/vim-rooter - Plugin to achieve this.

The reason why I would love to this in Markor is because without it the awesome Marksman-LSP only provides a small subset of it's features. See: [Workspace folders, project roots, and single-file mode](https://github.com/artempyanykh/marksman/blob/main/docs/features.md#workspace-folders-project-roots-and-single-file-mode)
