### ISSUE TITLE
diff mode

### ISSUE THREAD

**Issue by evanjrowley** [gsantner/markor#2034]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

Requesting a feature whereby two notes can be compared, differences highlighted, and edited to merge the differences (i.e., diff mode).

The feature would be very useful for Markor users who are synchronizing their notes. Syncthing, for example, will create a whole separate note when it detects a conflict. It is currently difficult to manage these differences, especially for large notes, without a comparison feature.

### Information

Android version: 13
Device: Google Pixel 7
App Version: v2.10.8 (145)

### Source

F-Droid

### Format / File type

Not specific

**Comment by harshad1** [comment]
This is really hard to do well and IMO is outside the scope of what would be feasible to implement. Personally, the few times I have had to do this, I just run diff in Termux and then resolve the resulting output file in markor.

**Comment by lrq3000** [comment]
@harshad1 A basic diff management can be done quite easily, Markor can just show the diff and offer the user to either keep current version, or use the newer version.

For the diff generation, it can be complex yes, but maybe there is no need to reinvent the wheel, but a library could be reused, such as [pandiff](https://github.com/davidar/pandiff)?

Automerge is an advanced method for diff resolution, most programs do not implement that anyway. Maybe there is some library that implements that, but otherwise I also think it's too complex and tricky to be done from scratch, because a badly written automerge can make users lose their notes.

BTW, SyncThing already produces two files when a conflict is detected.

**Comment by harshad1** [comment]
I meant that displaying a 2 pane diff (like vimdiff) would be hard.

I am still of the opinion that we should adopt a more Unix philosophy and use external tools whenever possible.

**Comment by gsantner** [comment]
> A basic diff management can be done quite easily, Markor can just show the diff and offer the user to either keep current version

It is not easy. It means Markor need to keep various versions of files _(=New Feature: File versioning / File history / Automatic backups / Automatic safety copies)_ and just besides, also implement a textdiff UI+algorithm. I'm not keen on the former.

Markor is not a version control system. Other software, like git for for example is better suited towards this.

Markor is a simple text editor and while it got many stuff over time I don't want it to get Godzilla. Like MsWord and co are, which is the reason after all that I created Markor, it's reason for existance. Because of being done with the lockin and bloat.

**Comment by lrq3000** [comment]
I understand the reasoning and I agree that the diff features should be more logically provided by the synchronizing softwares (eg, SyncThing). I just wanted to suggest a few tools that could help reduce development time if someone wanted to go this route.

**Comment by gsantner** [comment]
I sometimes too would love a tools like Meld (gtk) or vimdiff. But working with longer texts or multiple texts at same time is quite difficult on mobile due it's physical size. 

So it's a nice idea, but I would rather see it fitting to a own (diff) tool.
