### ISSUE TITLE
Title bar extends into status bar, Android 15

### ISSUE THREAD

**Issue by 6058aa27-6ced-4d77-952a-bf55d59351c2** [gsantner/markor#2387]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

When entering a file or the settings, the app takes up the whole screen rather than just the space below the status bar, making the UI at the top uninteractable and making it look odd.

### Steps to reproduce

1. Enter the settings menu through the three dots.
2. The UI extends under the status bar

### Information

Android version: Android 15
Device: Google Pixel 6
App Version: v2.12.5-0934 (240802)

Images for reference:
<img src="https://github.com/user-attachments/assets/1c5894b2-2594-46b6-ab86-828206b7fb2d" width="200"/>
<img src="https://github.com/user-attachments/assets/8ed8da47-fe29-4022-ab99-f1d367b2bd79" width="200"/>

### Source

git master branch

### Format / File type

Not specific

**Comment by 6058aa27-6ced-4d77-952a-bf55d59351c2** [comment]
> I am on a pixel 7 and I do not see this.
> 
> Does this happen on the latest release?

I tested on the latest nightly build. Are you on the Android 15 beta?

**Comment by harshad1** [comment]
I'm not on the android beta program, no

**Comment by 6058aa27-6ced-4d77-952a-bf55d59351c2** [comment]
I just had the same issue in Syncthing-Fork! I think this is probably caused by Android 15 then. Any idea what specifically causes this or how to fix it (or if it's a bug that needs to be reported to AOSP)?

![Screenshot_20240817-031329](https://github.com/user-attachments/assets/10858664-85e3-4585-9b39-c4ca3bd6eaf4)

**Comment by gsantner** [comment]
Maybe appcompat is not properly fully compatible yet

**Comment by mendhak** [comment]
I've just been upgraded to Android 15 and I can see this same problem.

I think this might be related to the [edge to edge feature](https://developer.android.com/develop/ui/views/layout/edge-to-edge). If your app targets SDK 35, then the app spans the entire length of the screen.

**Comment by chengnan049** [comment]
Pixel 6 same

**Comment by ryrona2** [comment]
Easy fix would be to change target SDK to 34 instead, and rebuild and release. Since all stock Google Pixel owners are being force upgraded to Android 15 since two days ago, and all GrapheneOS users will be done the same in two days, this issue starts affecting many now. Buttons to save and revert last change and so on are basically unclickable as it is now.

Problem likely introduced here:

https://github.com/gsantner/markor/commit/5de71d5e562e3b5289c08f88c074e8ce4761fad8#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R17

Proper solution is to implement proper handling of edge to edge. But other projects that have done that have had to do quite a few code changes and later fixups, so I suggest reverting to SDK 34 first, get that update out, and then try to calmly retarget the code for SDK 35 after that including all needed code changes.

**Comment by gsantner** [comment]
I would prefer it to be fixed instead of downgrading. Anyway Google will enforce upgrade to 35 in upcoming times.

**Comment by ryrona2** [comment]
I noticed the issue is much worse than just overlapping status bar. Actually the last 10 lines of the text document ends up under the keyboard, so you cannot see what you type at all if you are editing the end of a document long enough to fill your screen. Also, the bar with the editing options also ends up under the keyboard, and can only be accessed by minimizing the keyboard. But the keyboard automatically pops up again if clicking most of them, making it very tedious to use those editing options.

So not only do the UI not account for screen cutouts, but also no longer account for the space the keyboard occupy. The editor is mostly unusable in the current state.

Since you didn't want to temporaily revert to SDK 34, is there a time frame for when we can expect this issue to be resolved?

Would there be any help you would appreciate to get this issue resolved, ie that someone else works on it and make a pull request?

What I am asking is, do you intend to speedily resolve it yourself, or do you lack time, energy or access to Android 15, and this ticket thus is "patches welcome"?

**Comment by 6058aa27-6ced-4d77-952a-bf55d59351c2** [comment]
Thanks for writing this out, I also noticed this.

**Comment by gsantner** [comment]
> is there a time frame for when we can expect this issue to be resolved?

There was no meaningful fix suggestion or documentation, so no ETA. Generally, no ETAs for anything.

> Would there be any help you would appreciate to get this issue resolved, ie that someone else works on it and make a pull request?

Help is definetley

**Comment by CatsDans** [comment]
I can just confirm that at the moment it has become impossible to use the app normally on android 15. :(

**Comment by seanlano** [comment]
I've managed to temporarily work around this issue by **downgrading Markor to v2.12.3** – which has the target SDK as 33 and hence does not have the Edge-to-Edge Enforcement that Android 15 applies when SDK 35 is targeted.

**Comment by seanlano** [comment]
Apparently there is a way to opt-out of the Edge-to-Edge Enforcement policy: https://developer.android.com/reference/android/R.attr#windowOptOutEdgeToEdgeEnforcement

I'm a software developer but not for Android – but I'll see if I can figure out how to get that setting into Mark or, and create a PR for it.

**Comment by gsantner** [comment]
Please try the build from https://github.com/gsantner/markor/actions/runs/11489636870

**Comment by rovitotv** [comment]
The new build functions correctly on Google Pixel 8 Pro with Graphene OS Android 15/Build 2024102100.  Now I can push the save button and get to Markor's top menu bar.  Editing is noticeably slower for me I am not sure why.

**Comment by polyzen** [comment]
Working for me as well, also on Graphene OS/Android 15.

**Comment by seanlano** [comment]
I can also confirm Version `2.12.5-2319` fixes the issue for me

**Comment by acmpo6ou** [comment]
> The new build functions correctly on Google Pixel 8 Pro with Graphene OS Android 15/Build 2024102100. Now I can push the save button and get to Markor's top menu bar. Editing is noticeably slower for me I am not sure why.

This is because it's a debug build I think, the app is even called "Marder", instead of Markor.

**Comment by ryrona2** [comment]
I can confirm the build above resolves all the issues.

**Comment by gsantner** [comment]
Thanks for confirming.

Seems bad in Android SDK update that it's ""broken by default, opt out not to""" instead of """opt in to break/use feature""".

**Comment by grorico1** [comment]
Is there a way to get an APK for 2.12.5-2319 ?

**Comment by gsantner** [comment]
Check the Actions tab on GitHub project

**Comment by 6058aa27-6ced-4d77-952a-bf55d59351c2** [comment]
> Please try the build from https://github.com/gsantner/markor/actions/runs/11489636870

Just got around to testing this, seems to work fine. Thanks!

**Comment by mauryask** [comment]
You can fix it as below

**1.** Enable edge-to-edge display

` EdgeToEdge.enable(this);`

**2.**  Apply the top inset as margin to your toolbar (or any custom view)

```
 ViewCompat.setOnApplyWindowInsetsListener(toolbar, (v, windowInsets) -> {
            Insets insets = windowInsets.getInsets(WindowInsetsCompat.Type.systemBars());
            ViewGroup.MarginLayoutParams layoutParams = (ViewGroup.MarginLayoutParams) v.getLayoutParams();
            layoutParams.topMargin = insets.top;
            v.setLayoutParams(layoutParams);
            return windowInsets;
        });
```

**Update your onCreate() method as below**

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Enable edge-to-edge display
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);
        
        Toolbar toolbar = findViewById(R.id.rootToolbar); // Or use some custom-view
        // Apply the top inset as margin to your toolbar
        ViewCompat.setOnApplyWindowInsetsListener(toolbar, (v, windowInsets) -> {
            Insets insets = windowInsets.getInsets(WindowInsetsCompat.Type.systemBars());
            ViewGroup.MarginLayoutParams layoutParams = (ViewGroup.MarginLayoutParams) v.getLayoutParams();
            layoutParams.topMargin = insets.top;
            v.setLayoutParams(layoutParams);
            return windowInsets;
        });
    }
```

Upvote if it worked for you: [https://stackoverflow.com/a/79713693/15251854](url)
