### ISSUE TITLE
Strange uncomfortable highlighting for 3+ levels of nesting

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#250]
- Markor v0.3.7 from F-Droid
- Nokia 6.1
- Android 8.1

When I create a list with 3 levels of nesting, the text at the third level and below becomes white on a light grey background 🤔

![](https://i.imgur.com/37IjCEp.png)

Is this a bug? It's uncomfortable on the eyes to read (in editor mode) or edit (the cursor just seems to vanish in these regions).

**Comment by gsantner** [comment]
This is because 4 spaces are interpreted as code block in highlighting.
Not sure currently about specification, but I think its just specified for 1-2 levels in commonmark.

In any case - we won't handle third level nesting seperatly - it would make a big performance impact for a rather low amount of use.

**Comment by contrapunctus-1** [comment]
@gsantner the CommonMark spec has atleast one [example](https://spec.commonmark.org/0.28/#example-257) of a list with >3 levels. Is this a flexmark-java issue, then?

**Comment by gsantner** [comment]
read again. this is mainly about highlighting performance

**Comment by harshad1** [comment]
@gsantner Would you accept a patch which adds an option to disable code block highlighting all together?
