### ISSUE TITLE
When sharing to QuickNote, have a clear separator

### ISSUE THREAD

**Issue by IzzySoft** [gsantner/markor#259]
If one shares multiple snippets to QuickNote, there's no separation and thus not clear where one note ends and the next note starts. Please introduce *an option* (as someone might like it exactly as-is) to always have a separator (e.g. an horizontal ruler) prepended to a new snippet if QuickNote is not empty.

<sup>(spin-off from #257)</sup>

**Comment by IzzySoft** [comment]
Cool, thanks! Another cliff-hanger. Just installed the update F-Droid published today, now can't wait for the next :wink:

**Comment by svemoe** [comment]
I liked it as it was (with no sepearator) :stuck_out_tongue: 
Because I shared urls to the linkbox and had a textfile with one url per line.
Is there now an option to change it back?

If not, maybe you could add an option to the settings where one can change the string that is added as separator.
That way everyone could have the separator he likes (or none if he leaves the texbox empty)

An other possibility would be to not add the seperator when one shares to linkbox.

Please tell me what you think :smile:

**Comment by gsantner** [comment]
Closing in favor #287
