### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by returntrip** [gsantner/markor#309]
#### General information
New to Markor,  great app BTW.
How can I insert nested lists? I have tried with 4 spaces indent but does not work.   

* **App version:** 
1.0.0

* **System:** 
Android O
#### Description
Unable to add nested lists

#### Log
NA

**Comment by gsantner** [comment]
Level 1+2 is specified in Markdown. 0,2 spaces does make it. 4 spaces is source code in Markdown hence cant do that.
For 3 levels use html UL


```
* l1
* l1
* l1
  * l2
  * l2
  * l2
``

**Comment by returntrip** [comment]
That works. The funny thing is that the Commonmark tutorial says to use four spaces:

https://commonmark.org/help/tutorial/10-nestedLists.html

**Comment by gsantner** [comment]
hehe weird :D. most parser refer to codeblock with 4 spaces (at any time), can't remember to have seen this above work at any parser  yet - at least our parser doesn't do that

**Comment by returntrip** [comment]
I think the reasoning is given in the specs: see "5.2.1 Motivation"

> Unfortunately, given the divergences between implementations, there is no way to give a spec for list items that will be guaranteed not to break any existing documents. However, the spec given here should correctly handle lists formatted with either the four-space rule or the more forgiving Markdown.pl behavior, provided they are laid out in a way that is natural for a human to read.

So one could use 2 or 4 spaces and should work anyway

**Comment by gsantner** [comment]
Well the common standard for markdown but not THE STANDARD :crab:

**Comment by matt-snider** [comment]
@gsantner @returntrip 

This behaviour in Markor confused me and I didn't realize that the highlighting was supposed to be a source code block. 

Just wanted to chip in and say that both GitLab and GitHub allow 4 spaces to indent nested lists and it doesn't result in a code block. Which implementations translate 4 spaces to a code block?

**Comment by kankaristo** [comment]
Markor is handling code blocks wrong, and not according to the Markdown standard.

John Gruber is one of the original creators of Markdown, and Wikipedia lists his site as the homepage of Markdown:
https://daringfireball.net/projects/markdown/

The site has examples of lists:
https://daringfireball.net/projects/markdown/syntax#list

-----

Many of the examples break inside Markor:

```
To make lists look nice, you can wrap items with hanging indents:

*   Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
    Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi,
    viverra nec, fringilla in, laoreet vitae, risus.
*   Donec sit amet nisl. Aliquam semper ipsum sit amet velit.
    Suspendisse id sem consectetuer libero luctus adipiscing.
```

Markor renders the indented lines as code blocks, which they are not.

There are also examples of block quotes and code blocks nested inside of lists (note the empty line before each, and the mentioned 8 spaces of indent, so that the code block is rendered inside the list):

```
To put a blockquote within a list item, the blockquote’s > delimiters need to be indented:

*   A list item with a blockquote:

    > This is a blockquote
    > inside a list item.

To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs:

*   A list item with a code block:

        <code goes here>
```

-----

Nowhere on that site is it mentioned that Markdown only supports up to 2 levels of depth in lists.

The site also has a sample parser:
https://daringfireball.net/projects/markdown/dingus

It handles lists with many levels of depth just fine:

```
- test
    - test
        - test
            - test
        - test
    - test
- test
```

All of the examples, and the example parser requires an empty line before a code block:

```
Some text
    not a code block

Some text

    code block
```

-----

Markor's implementation of Markdown seems to be quite badly broken, at least regarding lists / code blocks.

This is unfortunately making Markor unusable for me...

**Comment by gsantner** [comment]
Please direct **render** issues to the Markdown parser it uses, Flexmark. Also, please check with CommonMark spec.

**Comment by kankaristo** [comment]
CommonMark also allows lists to arbitrary depth, and shows an example with indented text inside a list item:
https://spec.commonmark.org/0.29/#example-277

Their example parser:
https://spec.commonmark.org/dingus/?text=-%20foo%0A%20%20-%20bar%0A%20%20%20%20-%20baz%0A%0A%0A%20%20%20%20%20%20bim%0A

I doubt the issue is with Flexmark either, their repo has CommonMark tests:
https://github.com/vsch/flexmark-java/blob/master/flexmark-core-test/src/test/resources/core_commonmark_compatibility_spec.md

One of those tests looks like this (search for "Test shows where the boundary switch to indented code occurs"):

```md
-   test
    - sub item

         sub item child para

          indented code
```

The above link also has the HTML result below the Markdown text, and the test parses according to the CommonMark spec (only the last line becomes a code block). In "regular" Markdown none of the above would become a code block. But that's fine, it's a bit of a weird example, and I'd be happy with either Markdown or CommonMark.

The CommonMark sample parses also parses it correctly (no surprise there):
https://spec.commonmark.org/dingus/?text=-%20%20%20test%0A%20%20%20%20-%20sub%20item%0A%0A%20%20%20%20%20%20%20%20%20sub%20item%20child%20para%0A%0A%20%20%20%20%20%20%20%20%20%20indented%20code

But Markor parses that same sample so that even "sub item child para" becomes a code block, although it should be a regular paragraph in both Markdown and CommonMark.

I'm guessing the issue isn't with the CommonMark spec or with Flexmark, but possibly with how Markor *uses* Flexmark.

**Comment by gsantner** [comment]
I don't know, I use lists, I use nested lists, and so do a lot of users. If you want a nested list, have proper indendation levels and a `*/-` list prefix. If you want code block, use code block \`\`\`. And if you want to use code block by indent with 4 or more spaces, have some line in between and make it.

And if you need something very special , you can always add html.

**Comment by gsantner** [comment]
I don't know, I use lists, I use nested lists, and so do a lot of users. If you want a nested list, have proper indendation levels and a */- list prefix. If you want code block, use code block ```. And if you want to use code block by indent with 4 or more spaces, have some line in between and make it.

And if you need something very special , you can always add html. Or rethink if your text is not too complex structured, and have it understandable for you and the one who will read it. Especially on mobile device, having everything prefixed with like 6+ spaces look like hell.

**Comment by kankaristo** [comment]
But even the below breaks in Markor?

```
- test
  - test
    - test
      - test
```

In Markor's edit mode, the last line renders as a code block, which it is not.

If I indent the list with 4 spaces (like I normally do), Markor breaks even earlier, and the last line here renders as a code block in edit mode:

```
- test
    - test
        - test
```

**Comment by gsantner** [comment]
Edit Mode != View mode. Edit mode is there to preview it fast while editing, running FULL markdown conversion or highlighting every millisecond is out of scope, so it uses simplified one. It is known that it works that way in edit mode and will stay like that for now.

And renders find in view mode:
```
- test
  - test
    - test
      - test
```

**Comment by kankaristo** [comment]
Unfortunately, I spend most of my time in edit mode, so I'll probably need to look for another Markdown editor for Android...

**Comment by gsantner** [comment]
Well you are free todo so - if you want to start contributing, and improve it - please do so.  
Only talking does not improve it 😃 .
