### ISSUE TITLE
MD: Remove current list item if enter pressed and nothing entered

### ISSUE THREAD

**Issue by Alzarath** [gsantner/markor#336]
#### General information

* **App version:** v1.1.2 Google Play
* **System:** Android 8.0.0, Samsung Galaxy s9

#### Description

Currently, we need to hit enter and delete the last 2 characters to exit a list or go down, create a new line, and go back up.

In some markdown software, hitting enter after an empty item (i.e. hitting enter twice from the current item) will remove the empty item (typically without creating a new line) instead of the current behavior of creating yet another empty item. This makes it quick and easy to 'exit' a list. I would like that functionality in Markor.

**Comment by stupidly-logical** [comment]
Working on this.

**Comment by rancidfrog** [comment]
But what if users want that empty item to space out the list?
Why would you expect enter key to act in a different way. If you want backspace and delete keys already exist.
I want double space key to do something else. These are more specific to keyboard app than this app.
Key replacement should be for keyboards.
Also, why not have empty item?

**Comment by stupidly-logical** [comment]
@gsantner  Can you help me out with figuring out the code which inserts the date on pressing enter.

**Comment by rancidfrog** [comment]
You will need new setting to check if enter key manipulation enabled or not:
https://github.com/gsantner/markor/blob/1bb1485c5a93fa0f3a14ae547a714c2a01ecb30a/app/src/main/java/net/gsantner/markor/format/todotxt/TodoTxtAutoFormat.java#L67

**Comment by rancidfrog** [comment]
My mistake, from description it sounded like todo list item

**Comment by rancidfrog** [comment]
So,
https://github.com/gsantner/markor/blob/1bb1485c5a93fa0f3a14ae547a714c2a01ecb30a/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownAutoFormat.java#L69L98 ?

**Comment by gsantner** [comment]
yes, but other classes in this package too, look for the invocation

**Comment by jakub231** [comment]
Hi can I work on this issue? Is it still open? Thanks.

**Comment by gsantner** [comment]
@jakub231 Yes please :D

**Comment by harshad1** [comment]
Looking at several popular editors (StackEdit, Libreoffice, Google docs), the expected behaviour is as follows:

1. If the list item has text then insert a new list item
2. If the list item is empty, then _delete the current list item_

```markdown
- foo
- bar <- CR here
```
Results in 

```markdown
- foo
- bar
- <- cursor
```

While 

```markdown
- foo
- bar
- <- CR here
```
Results in 
```markdown
- foo
- bar
<- cursor here, note that new line has been deleted
```

My understanding is that we can't modify the existing `Spanned` in `filter()`.
So, if we want to implement this, the solution will have to be 2 step:
1. Detect this scenario in `filter()` and insert nothing (i.e. replace "\n" with ""
2. Delete the leading bullet / number / checkbox in some handler which runs _after_ the text has been inserted.

Questions are:
- [ ] Do we want to implement this behavior
- [ ] Does the approach I have described seem correct.
