### ISSUE TITLE
Dialog with Special Characters (like Ω, ∂, ..)

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#359]
#### General information

* **App version:**  v1.2.2
* **System:** Android 7.0.1

#### Description
I recently worked on some electronics related documents and found out that I can't type OHM (Ω) somehow with my touch keyboard. Hence I then opened browser, found the symbol and copied it.
It would be great to have an dialog popping up which shows special characters with a possible short symbol name, so search works. 
What's my favourite so far is how LibreOffice has this implemented, you can use that as a reference whats possible and see visually what this is about. You can use the existing SearchOrCustomDialog class if you want, the first and biggest part is to populate the list (get symbol + it's name).

![screenshot_20181001-201023](https://user-images.githubusercontent.com/6735650/46307262-ba975600-c5b6-11e8-86c4-22e1eac2922d.png)

**Comment by jashasweejena** [comment]
I would like to work on it!

**Comment by gsantner** [comment]
To everyone: feel free to start on this.

**Comment by jashasweejena** [comment]
Do you actually want me to add a bottom sheet in the activity for creating notes, which opens up a dialog containing the symbols?

**Comment by gsantner** [comment]
No, it should be a dialog. Please don't modify activity for this. To trigger the dialog you can temporarly uncomment e.g. the delete_line textaction and run your new dialog.

**Comment by jashasweejena** [comment]
Okay! Will try :)

**Comment by gsantner** [comment]
@jashasweejena 
Have you started on this / do you have something other can start off with when they go for this?

**Comment by petraspeter** [comment]
I find this one quite interesting, and since @jashasweejena didn't respond I took a look at special characters.  
So I parsed almost 300 unicode blocks and place them as unicode.xml. You can find the whole list of blocks & .xml file [here](https://github.com/petraspeter/unicode-blocks) :blush: It look like this:  
  
![image](https://user-images.githubusercontent.com/22313019/50424636-a9817c80-0867-11e9-9c3f-4a81ea351809.png)
  
and  
  
![image](https://user-images.githubusercontent.com/22313019/50424644-bef6a680-0867-11e9-92ab-67d35430db74.png)

So I think we could select wanted subset, generate name the same way as I did for .xml + add suffixes and retrieve data from there. Each position in `_name` & `_code_point` should be paired correctly, so I didn't see problem there.

I have a quick idea how could layout look like, since at phone there wouldn't be so much space. 
![image](https://user-images.githubusercontent.com/22313019/50425977-641e7880-0882-11e9-8966-070efa41c682.png)

PS: Maybe there could be also button add & remove to/from Favorites & Favorites subset could be gained.

**Comment by gsantner** [comment]
@petraspeter 
Thanks for comment!
As of data:
* I'm feeling like putting the 3MB in app is little too much just for this, agreeing that a sublist would be better :D. App has like 5MB as I remember, just for reference
* Design/Layout O.K. as is - would not make any final propose as there is always some way to do it better, which you find while doing it.
* Favs - I would not recommend that, but more like "recently used 10 on top"
* Data: can this be generated at runtime too? Where is the english string coming from? 
* Is there an localized version available, without letting Markor translators do the job?

**Comment by petraspeter** [comment]
* I paresed it from [here](https://www.compart.com/en/unicode/block), supported lang are: EN, DE, FR
 * `Deprecated:` We can parse it directly from web, but then it won't support offline mode
   * Problem could be that page has to be always accessable and if there became some change it could break it.
   * As solution we could parse each block into separated file and store them somewhere on web and access that.
 * There is [Character.UnicodeBlock](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.UnicodeBlock.html) I took a quick look at some ideas how could we get data from there yesterday(or rly early this morning) and I thought it won't worth it, since it looks like you have to loop through each Code Point(CP) and check if it belong into selected Uni Block.  
But as I relize this could probably be the best way how to make it.
   * Via reflection we should be able to get names of all Uni Blocks. So when we open dialog, we loop through it and map Name of Uni Block with first CP.
     * We can also get name of CP form there so we end up with **Set\<Character\> specialChars** & **Set\<String\> names**
     * But there will be a problem with language, since name will be given from java
 * For localizatiob there is [Common Locale Data Repository](http://cldr.unicode.org/) for unicode, but my first impression from whole Unicode official data is, that they are heavily to use and it's also a big amount of data.

**Comment by gsantner** [comment]
The `Character.UnicodeBlock` was what I meant specifically with my question for generation. In no way I want to make http-requests to get unicode table :smiley: .

**Comment by contrapunctus-1** [comment]
Shouldn't this be implemented in the concerned software keyboard, or maybe in a separate app, so that it can be used by all programs instead of just Markor?

**Comment by gsantner** [comment]
the thing is most people use the default keyboard (like me) and dont need special stuff for like the 99% usecase.

We may not need any at all, just stuff that is more common but still not on most keyboards. Like Ohm or Sum sign for example

**Comment by gsantner** [comment]
Somebody working on this currently? Or started on it? Please open pull request even if unfinished/WIP.

@petraspeter @jashasweejena

**Comment by gsantner** [comment]
I'm closing this as I don't really would like to add a generic full blown list of special chars to the projects which takes big amount of space. 
Instead I will go just the way to add things when required, e.g. added `Ohm` to the list of special chars today.
