### ISSUE TITLE
Markdown: Math block rendering

### ISSUE THREAD

**Issue by tpikonen** [gsantner/markor#381]
#### General information

* **App version:** 1.2.2
* **System:** SailfishOS

#### Description

Nice to see markor supporting Tex / KaTeX syntax for math, however I noticed that the 'block' syntax for equations, i.e. the $$ delimiter does not work.

The text between the '$$' delimiters should be rendered as math, centered and with a larger font. Currently $$ is interpreted as empty in-line math section and thus does nothing.

For a test case, see e.g. the 'Examples/block' section here: https://github.com/waylonflinn/markdown-it-katex/blob/master/README.md

**Comment by gsantner** [comment]
Currently only inline is enabled, at `MarkdownTextConverter.java`.

Open for pull requests to change the behaviour to enable block math parsing with katex too.

**Comment by gsantner** [comment]
@tpikonen 
Block rendering is now enabled. But note that as we use markdown here, you somehow have to stop it do it's work. You can do it by wrapping the math block into a `div`. Also, if you want to have empty newlines in plaintext, you have to add `zero-width spaces`, otherwise you will get `<p></p>`  in converted text (which in turn will make katex stop work). You can find that symbol in the special keys menu.

![screenshot-2018-10-15__23-36-43](https://user-images.githubusercontent.com/6735650/46980388-af731880-d0d4-11e8-8ea3-a0abca3621a5.png)
![screenshot-2018-10-15__23-44-44](https://user-images.githubusercontent.com/6735650/46980390-b0a44580-d0d4-11e8-8dee-1f3c67ae1379.png)
![screenshot-2018-10-15__23-44-47](https://user-images.githubusercontent.com/6735650/46980392-b0a44580-d0d4-11e8-97e5-6c1b19c8daed.png)

**Comment by gamdow** [comment]
I've been looking for a way to view Markdown + Latex documents, written using [Atom](https://atom.io/), on my phone. Markor looks like a great candidate, but there is a discrepancy in the way block equations are treated. In Atom, it appears that text is either rendered as markdown or Latex, but in Markor it is rendered as markdown and Latex.

I guess there isn't a standard for these, but is there a way to get them working consistently? (the `<div>` trick breaks Atom's markdown/Latex rendering). I'm not an expert at either, so I'm wondering if this is a fundamental issue, or a quick fix.
