### ISSUE TITLE
Toggle checkbox status in preview mode

### ISSUE THREAD

**Issue by de-es** [gsantner/markor#497]
I have a lot of extensive nested checkbox lists. It would be cool if I could easily toggle the checkbox status in preview mode because in edit mode it is kind of cumbersome - first select the correct line, then click the checkbox in the toolbar - and error-prone. But I don't know if this is technically possible somehow.

**Comment by gsantner** [comment]
Preview/View/Representation is read-mode only and it's not planned to add any edit/save features to it.

**Comment by de-es** [comment]
Thanks for the quick feedback.

**Comment by iclanzan** [comment]
For what it's worth I also really wish it was possible to toggle checkboxes by tapping on items in preview mode.

**Comment by georgefst** [comment]
Same. I'd like to understand where @gsantner's opposition to the idea comes from. It is my only real frustration with this app. I actually use a separate app just for this purpose when e.g. I'm shopping and need to quickly tick things off my list. It's just too fiddly with Markor.

**Comment by gsantner** [comment]
@georgefst   
A few.....:

* I don't want any !!file write!! or modify access from the web. What is used to display is a WebView. Using CSS and JS to display Markdown (&others) contents properly, styled and functionial (JS for things like mermaid,prism & more).
* It is called VIEW mode for a reason, it's there for VIEWing not for EDITing. Just like when you print out something with a printer and use your pen to check some checkbox. It's there, fine. But not written somewhere except there on this printout.
* The content is not the same. What you see in view mode is usually a big rendered html document. Checkbox or whatever in HTML can be completley different rendered then what you write in editor. So `"[x] Hello >"` and `<input type="checkbox" checked>Hello &gt;</input>`. Rather a simple example, but generally said output doesn't map to input. Markor is not a HTML to `<anything>` converter. And Markor supports a lot of formats, not just Markdown. You can make checkboxes in literally anything. In zim, in todo.txt, in Markdown...in a plain HTML file.

> opposition to the idea comes from. It is my only real frustration with this app. I actually use a separate app just for this purpose when e.g. I'm shopping and need to quickly tick things off my list. It's just too fiddly with Markor.

1. If you want to quickly check off things your list: You already have the file opened (Editor). Go to the thing you want to check. 
2. Press the check button on the bottom. DONE. thats it.

[screenrecord-2022-09-02_01.16.58.webm](https://user-images.githubusercontent.com/6735650/188028208-6d3daa24-2c5a-4362-94e9-38a90899cb9d.webm)

> I actually use a separate app just for this purpose when e.g. I'm shopping

Well then..do that? Don't know what this information should be worth, I don't care what else somebody uses, whatever fits the purpose. Markor allows you todo much stuff and if you are not in to using it the way it it's described to work, it's your decision.

**Comment by georgefst** [comment]
Hi. I am genuinely grateful for you typing out such a thorough response, so I hope the following does not offend. I'm just trying to make sure you see my viewpoint.

> 1. If you want to quickly check off things your list: You already have the file opened (Editor). Go to the thing you want to check.
> 2. Press the check button on the bottom. DONE. thats it.

Yes, but this takes twice as long as a single click. For a very common interaction, that's significant.

> > I actually use a separate app just for this purpose when e.g. I'm shopping
>
> Well then..do that? Don't know what this information should be worth, I don't care what else somebody uses, whatever fits the purpose. Markor allows you todo much stuff and if you are not in to using it the way it it's described to work, it's your decision.

Well, there are obviously downsides to what I'm doing. e.g. it's awkward constantly flicking between two apps (with similar functionality). I'm interested in discussing how the process could be streamlined (for myself and other users) by improving Markor itself.

> It is called VIEW mode for a reason, it's there for VIEWing not for EDITing. Just like when you print out something with a printer and use your pen to check some checkbox. It's there, fine. But not written somewhere except there on this printout.

> Viewing is a export. a backup. a copy. a preview. it's not editing the file.

These are pretty philosophical objections. If something improves UX, that's what matters. On the other hand, I had mistakenly assumed these were the only reasons why you were against changing this, whereas you've now helpfully poitned out that there are also significant technical challenges.

Anyway, I understand that you don't want to change this. Maybe some day I'll build my own minimal Markdown+HTML app, with editing in both modes (maybe Pandoc could be useful?). But I'll probably never get round to it. On that note, thanks again for building Markor! It does 95% of what I want from such an app, and the rest can be worked around.

**Comment by gsantner** [comment]
> Maybe some day I'll build my own minimal Markdown+HTML app

Hehe, as you already say - just Markdown. And Markor is more then just Markdown - thats what I mean with `<anything> to html or the other way from html to <anything>`

**Comment by georgefst** [comment]
> Hehe, as you already say - just Markdown. And Markor is much more then just Markdown - thats what I mean with `<anything> to html` or the other way `from html to <anything>`

Yeah, exactly. That's why I'd focus on Markdown, as that's all I care about anyway.

**Comment by conceptionist** [comment]
It works in view mode in Org format, but not in view mode in MD. In ORG format, a lot of useful MD-Code is missing.

I also strongly support checking in view as an extremely leveraging UI improvement - I searched for something like EasySync mainly because Task.org does not allow it and Nextcloud does not work in steel buildings like supermarkets.

Just adding user feedback - I am aware and do respect that the final say is with the maintainer.

**Comment by gsantner** [comment]
> In ORG format, a lot of useful MD-features is missing.

Yes, thats what I was mainly concerend about. At the end, a lot of things are format specific and outside of Markdown & todo.txt there is very little contributions going on. But people do and will open bugs and stuff about such situation. Hence difficult topics.

**Comment by novamax** [comment]
I realized the issue is even more complicated:

You cannot interact with checkboxes in markdown preview, but in org-mode preview, but the status is actually not stored: If you reload the preview or go to edit mode, the checkmark is gone again, which is are somewhat misleading... I completely understand that you do not want writing from HTML, but Is this HTML preview, too? Or is there a chance to implent saving the checkbox status in org-mode? In this case, I could just use org-mode files for the frequent use case fo checkbox interaction... (and many others, judging from the many issues and contributions to this aspect here).

I guess from the users perspective, edit and html preview mode are not easily discerned technically (as a dev does). From the ergonomics point of view, markdown would need three modes, like editing the content, user interaction with given content (like checkboxes), and plain preview. I am not sure if the second mode can be somewhat implemented easily (even in a reduced form), but I think this is what most people look for...

Or at least drop the checkmark interaction in org-mode when it has no effect by intention.
