### ISSUE TITLE
Sort option not persistent

### ISSUE THREAD

**Issue by Offerel** [gsantner/markor#545]
In 1.7.5 if i try to sort the files by date, sorting is fine. However if I close the app and reopen it, the default sorting order by name is restored. 

Please save the sorting order.

**Comment by retromore** [comment]
Having troubles with this too, previously I had my default sorting set to last modified date, now it reverts to a-z sorting every time I open Markor.

**Comment by nehrwert** [comment]
same for me.

**Comment by bigtreiber** [comment]
I can confirm that issue too

**Comment by mogarithm** [comment]
Highest priority issue in my opinion. Should be a relatively simple fix.

**Comment by gsantner** [comment]
> Highest priority issue in my opinion. Should be a relatively simple fix.

Than please do the fix and send PR :-)

**Comment by gsantner** [comment]
Sorting was previously only an action (as in sort the list, now!), not an setting. That's why it was not saved/restored :wink: .

* #545 Now it is an option and restored. Theres also new UI indicating which option is currently selected
* #546 There is also a new option to show/hide dotfiles (so filenames starting with a `.`
* `There is =` in code. Not released yet, wait for the update to be released.

![screenshot-2019-06-20__16-37-06](https://user-images.githubusercontent.com/6735650/59857712-02d6ee00-9369-11e9-9200-b1c21bdf2016.png)

**Comment by Offerel** [comment]
Many thx. Works great.
