### ISSUE TITLE
Wrap lines when zooming md preview

### ISSUE THREAD

**Issue by Henry78** [gsantner/markor#562]
#### General information

* **App version:** 1.8.0
* **System:** Android 7.1.1

#### Description
Pinch zooming a Markdown preview (to increase readability/font size) doesn't wrap lines. I suggest wrapping lines is an option/default. 

Related to #466?

**Comment by gsantner** [comment]
Well zooming text does exactly that on mobile..to zoom text as is. I dont expect something else

**Comment by Henry78** [comment]
Any idea on how to make text more readable from a distance? 

My use case: Looking at a recipe while cooking, often a few meters away from tablet. As I stated, I'expect the text to stay readable all the time, except preformatted, code block etc.

**Comment by gsantner** [comment]
Whats displayed in view mode is simple html in a browser view. With the inject options you have full control over how everything is looking. You have full possibilities via javascript and css. 

Otherwise, there is a global font size setting, you can increase the size there and it will take effect on edit+view.

**Comment by gsantner** [comment]
I'm closing this as this is only Q/A/Discussion. Still open for comments.
