### ISSUE TITLE
White flash between screens

### ISSUE THREAD

**Issue by aluchuk4c** [gsantner/markor#568]
Screen flashes to white. Very inconvenient when trying to use dark mode. This occurs when opening files or going back to the selection. Doesn't happen when swiping between files, or when multiscreen option is disabled. Also occurs when app is first opened. Most noticeable after selecting the markor appearance theme. 

* **App version:** 1.8.0 (70) installed from play store.
* **System:**  9.0.5 OnePlus6

**Comment by gsantner** [comment]
switching between activities. its not possible to turn off as the white comes from android itself. app content is colored dark as soon possible.

**Comment by Russe** [comment]
I noticed this white flash as well when starting Markor.
The settings of Markor are "Dark Theme".
But when this white flash comes from Android itself, why there are other apps starting without this white flash (e.g. Threema, Suntimes, Voice, Feeder)?
Maybe there's something else which can be optimized to avoid this white flash when starting Markor?

**Comment by garret** [comment]
Would it be possible to reopen this issue? I am mainly bothered by the white flash when the app opens when all my system/apps are set in dark mode. I know for certain that it not an unsolvable fix as also recently the app Lemmur had the same issue and was fixed in the latest update. 

References: 
- https://github.com/krawieck/lemmur/releases/tag/v0.7.0
- https://github.com/krawieck/lemmur/pull/257
- https://github.com/krawieck/lemmur/pull/256
