### ISSUE TITLE
Encrypted documents feature

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#60]
Add support for encryption to Markor. You can maybe use an custom extension for that, so it can be better differntiated, e.g. `.enc` or `.aes`

The project doesnt need some fully blown up all-in-one crypto lib. Maybe <https://github.com/tozny/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java> has everything needed.

Password **must not** be stored anywhere on storage. It can be cached (`KeyValuePairs(File, String)`), but passwords in cache should be removed e.g. after 5 minutes (will be configureable in options then).

**Comment by AniketSK** [comment]
@gsantner if you're willing to up the minsdk to 18 instead of the 16 you have now, the [Android Keystore System](https://developer.android.com/training/articles/keystore.html#SecurityFeatures) could be used.
Do you think this would be appropriate?

Also, if you're willing to go up to 19 and add RxJava support, there's an excellent, 100kb [lib](https://github.com/afollestad/android-secure-storage) that will make using encrypted notes super readable and clear. 

Though the adding Rx part of it alone will bump the size 600kb. For a final size of 3.1Mb over the 2.4 you have now.

**Comment by gsantner** [comment]
@AniketSK No, I don't want to go further than API17, because I know many people with this people who told me thats pretty much the only foss app with the capabilities available that can be used on that level. And because I do manage 1 device with that level too :D

**Comment by AniketSK** [comment]
@gsanter cool, I'm up for the challenge! I really like the structure of your app, your build.gradle has been an education for me. I'm going to take a crack at it with the code you referenced in the first comment.
Do you mind if I move the saving and editing features of NoteActivity to the MVP architecture, is there a different one you'd prefer? Just the least change I need to make to save and open. It'd help me write tests for the encrypting/decrypting.

**Comment by gsantner** [comment]
theres another issue open for rewriting NoteActivity itself, issue #21 . The target there it too to merge EditActivity and PreviewActivity to one, so both get e.g. the same share-to functionalities. Yes you can go any way you want, be it MVP or MVC, but I would apply to you to not add a huge set of dependencies just to realize that :)

**Comment by AniketSK** [comment]
@gsantner I'd just like to use RxJava maybe one of its android specific libs, no other dependencies. I was surprised at what a low footprint your app has, I'll preserve that!
Cool, I'll take up #21 as well.

**Comment by gsantner** [comment]
@AniketSK Did you start the rework / will you do that? Because waiting this is blocking development currently

**Comment by AniketSK** [comment]
@gsantner Yes I did, I ran into a snag with the webview to image sharing notes. But I'm on it.
I saw that you have pending merges on other things that would require some change on my side, just mere those, I'll deal with it.

**Comment by Grunthos** [comment]
For portability and reliability reasons, why not use OpenPGP. It is avaialble on android (an app), linux, macos and windows. This would keep the notes portable.

**Comment by gsantner** [comment]
That one way to do it, yep. The target is still to be independent of other apps, so one can use encryption/decryption without having OpenKeyChain/AGP installed. This means there can be two options here, but I would go for the latter first

**Comment by Grunthos** [comment]
Fair enough; produce PGP stuff via bouncyCastle? Portable and self-contained.

**Comment by gsantner** [comment]
Possible. The thing with GPG is that you rely on some external thing, either an app or an keyfile. I don't know yet how it's best to handle this, even more where and if markor should store keys at all.

**Comment by gsantner** [comment]
@AniketSK @Grunthos 
Somebody working on this or want to start? ☺

**Comment by Grunthos** [comment]
@gsantner Happy to keep discussing then once we have an agreed plan, look at doing it (if plan suits my knowledge base).

There are some basic assumptions we need to lock in first:

1. Why are we encrypting?

I assume so that cloud backup can't be data mined and so that a person who steals the phone has a low chance of reading notes.

2. Do we want people to enter a passphrase each time they read/write an encrypted note?

I assume no; we would need to cache keys for some (user-selectable) time limit (or maybe until the note is saved?). We would probably want a 'forget cached keys' button, and maybe a "forget keys on sleep" setting, or ....other things

3. Do we want different keys on a per-note basis?

I assume no...but not sure

4. Do we want to allow key-recovery?

I assume no. I looked at this once before and it's a security nightmare. The problem with not providing it is people will say "I forgot my password, please help". We would need to be clear on the warning.

**Comment by gsantner** [comment]
1) to keep information private

2) No, and plan sounds good. For the settings I can assists, its quite easy and done fast.

3) Yes! While Markor is quite centered around the notebook, I still want to be able to open a file somewhere from the filesystem and be able to enc/dec it :). Basically some Hashtable<PathHashSomething, KeyInfo>. Of course one then use one key for everything too, but different keys should be possible.

4. No. In no way this is and will be a plan.

5. The general plan is to have interoptability, this should work for any crypto if the same algo and keysizes are used. GPG/Asym is of course an option too, but my goal for Markor is to be useable on any device without deploying external apps or keys (I do e.g. not store GPG on any mobiles). I leave it open which algo(s), but maybe AES and GPG is somewhat a nice goal.

**Comment by Grunthos** [comment]
1. This is clear; but how private? Do we want to erase all cached keys when the phone sleeps? Are we trying to keep it private from google or cloud providers, or anyone who gets our phone?

3. AES/CBC or similar can do a password-per-file quite easily, but we get back to having to cache keys or typing passwords a lot. Also, on some phones even just 10,000 hash iterations can be notably slow when mangling passwords.

4. Fine. 

5. I'm not an expert, but GPG is certainly a 'standard', I'll have a look and see what I can find about any standard ways of storing AES messages.

**Comment by gsantner** [comment]
1. A good midway between usabilty and paranoid :D. Well, the key/password should not leave the phone. For GPG I think OpenKeyChain already has things builtin (if you go for that).

2) Yes, cache. and I think of using some sort of default password (which yes has to be stored on disk). Performance shouldnt be the problem, onetime decrypt after read, encrypt on write

4) Basically you can do aes very simply on a bash/shell. Thats what I would e.g. expect to be openable with markor (ofc same keysizes etc)

**Comment by Raprockguy19856972** [comment]
People should not be fucking with one another on a computer or cell phone like that. It's none of my business but y'all tactics are pretty fucking awesome

**Comment by gsantner** [comment]
This is going to be too much for a lightweight app.

closing

**Comment by gsantner** [comment]
Thanks to @opensource21 there will be soon news on this :smile: :+1:
