### ISSUE TITLE
MD: Edit: Improve code bgcolor

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#693]
This is partially dup of #293

It's hard to see white on gray:

![image](https://user-images.githubusercontent.com/14617699/65832697-f818e700-e2cf-11e9-98e9-6dc83940080e.png)

**Comment by gsantner** [comment]
See also #242

**Comment by gsantner** [comment]
Highlighting colors are same between all formats, color schemes and styles. So that grey color has to work for both light and dark background color.

The color was already changed to be like above in long discussion with some others.
If there is a suggestion (hexcolor) for a different (ie. grey)  that works on lightbg-darkfg AND darkbg-lightfg please paste it here and lets add it if it works better.

**Comment by mgoral** [comment]
@gsantner How do you feel about leaving the defaults as they are now, but making them configurable?

**Comment by gsantner** [comment]
@mgoral No. HL colors constant.

**Comment by gsantner** [comment]
Currently not thinking of making change on that color, looked at screenshot and looked on phone..seems quite okay to me.

**Comment by 532910** [comment]
It is low contrast: https://webaim.org/resources/contrastchecker/?fcolor=8C8C8C&bcolor=FFFFFF

**Comment by dcdom2** [comment]
Please make this customizable (for both Edit and View modes). It is in the spirit of the app. Thanks
