### ISSUE TITLE
Feature: Search in View

### ISSUE THREAD

**Issue by 532910** [gsantner/markor#747]
#### General information

* **App version:** 2.1.5 97
* **System:** 16.0-20191017-microG-opnepus3

#### Description

    "Hey! Theres no search for view available.
    I only found a button in view which does go to editing instead.
    Can you please add search for View mode? Thanks."

**Comment by Anca07** [comment]
I would like to work on this issue :)

**Comment by gsantner** [comment]
@Anca07 
Great, thanks! Sure, go for it!

Have you used the app before, and in general understand what this is about? I'm sure @532910 will give you details when needed :smile: .

(From code pov: it's about webview and it's find/findNext methods)

**Comment by Anca07** [comment]
Hi @gsantner 

I played around with the app today, but since I liked it I think I will start using it from now on :smiley: 
If I understood correctly, the issue was that in view mode there is no search functionality (please correct me if I am wrong)
I have implemented a POC for search in view mode functionality (screenshots provided below).
Let me know if this is what is expected or if you have any suggestions.

![76730709_2178828135751202_625868385334329344_n](https://user-images.githubusercontent.com/18334788/67636113-d82c1180-f8d5-11e9-9bcb-5b10931d0114.jpg)
![73167841_449987422309431_3558630565106155520_n](https://user-images.githubusercontent.com/18334788/67636020-b8e0b480-f8d4-11e9-88aa-026d28196429.jpg)
![73019442_2613809975325052_4403713621666824192_n](https://user-images.githubusercontent.com/18334788/67636021-bda56880-f8d4-11e9-9d7f-3142e7485095.jpg)

**Comment by gsantner** [comment]
In browser you usually have a option to search current text. 
In the View mode there should be used the web search (webview.find(text)) method to search text instead of the editor text

**Comment by Anca07** [comment]
Okay, I got it now. Sorry for the misunderstanding.
I will make the changes accordingly.

**Comment by Anca07** [comment]
Hello again,

I have changed the search functionality according to your indications. 
Searching a string will highlight all the matches and  by pressing the arrow button the next occurrence will be selected.
Let me know if this is what was expected.

![74163828_483273262265845_3213825754450100224_n](https://user-images.githubusercontent.com/18334788/67639256-58626f00-f8f6-11e9-85aa-b4d8e805e685.jpg)
![73011843_933670997016386_8013476330777608192_n](https://user-images.githubusercontent.com/18334788/67639258-5f897d00-f8f6-11e9-8cfc-1065be55f0f7.jpg)

**Comment by 532910** [comment]
> Searching a string will highlight all the matches and by pressing the arrow button the next occurrence will be selected.

Sounds

> ![73011843_933670997016386_8013476330777608192_n](https://user-images.githubusercontent.com/18334788/67639258-5f897d00-f8f6-11e9-8cfc-1065be55f0f7.jpg)

and looks very nice!

The problem that see here is the right colors. On the screenshot above: what selection is the "current one" and what is "all other"? I'm for using green background for all matches and green foreground (or yellow/orange background) for the current one.

**Comment by gsantner** [comment]
->> #754
