### ISSUE TITLE
todotxt: Allow to insert tags/categories with multiple ++/@@

### ISSUE THREAD

**Issue by aisbergde** [gsantner/markor#957]
#### General information

* **App version:** 
* **System:** 

#### Description

I use some context / list entries starting with double @, like `@@WartenAuf`, `@@Irgendwann`, `@@Test`

The main reason is: these are some meta-lists, they should be ordered and marked separately and maybe there are some other reasons. 

This is conform to the todotxt syntax. But Markor has some issues with these entries. The list of list entries is strange and they can't be assigned from the list list to an entry if they are not right in the list. The list startes

- "
- Irgendwann
- Test
- WartenAuf
- abc"

Could you handle @@ (and maybe @@@, who knows)?

**Comment by gsantner** [comment]
it should be as easy as changing regex from @ to @+.

Open for PR.

**Comment by aisbergde** [comment]
> it should be as easy as changing regex from @ to @+.
> 
> I suggest to do the same for plus ( `[+]+`).

I could fork and do, but I don't know where in the code. Any hint?

**Comment by gsantner** [comment]
sttcommander.java

**Comment by gsantner** [comment]
@aisbergde 

Do I understand and see right: There is no issue with highlighting. ++/@@ already works fine on master. Also there is no issue that they are picked up by search/insert. It also doesn't matter where +/@ are, it works at begin of line, end of line and anywhere inside the line. 

BUT, when pressing insert tag/category (+/@) it's always inserted with one +/@. This being what your issue is.

![video_2020-06-11_16-05-52](https://user-images.githubusercontent.com/6735650/84394629-baa18300-abec-11ea-9fcf-ffed51da761d.gif)

Is this correct? Or am I missing something?  
If so, it's not at all something about regexes and it's only about how tags/contexts are **selectable at dialog** and **how insert works**.

**Comment by aisbergde** [comment]
> Is this correct? Or am I missing something?
> If so, it's not at all something about regexes and it's only about how tags/contexts are **selectable at dialog** and **how insert works**.

This is what I mean.
I don't know where and how `sttcommander.java` is used. You wrote about this place and maybe this is used for dynamically building the list to select entries, which is currently wrong.

**Comment by gsantner** [comment]
@aisbergde 
No worries. Well currently it's intentionally reduced to just title (without `@/+`). And that logic ensures theres only title and a single `@/+`


![grafik](https://user-images.githubusercontent.com/6735650/84569433-0d5a7680-ad76-11ea-9423-0962bb20f328.png)

**Comment by harshad1** [comment]
This appears to be solved now
